// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class ActiveProcessInvoice
{
    public int Id { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public string belnr { get; set; }

    public string bldat { get; set; }

    public string bukrs { get; set; }

    public string dagitimkanali { get; set; }

    public double? dmshb { get; set; }

    public string faedt { get; set; }

    public int? gjahr { get; set; }

    public string zterm { get; set; }

    public int? activeProcessId { get; set; }
}