// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class ActiveProcessVekalet
{
    public int Id { get; set; }

    public int VekaletVerenId { get; set; }

    public int VekaletAlanId { get; set; }

    public DateTime Tarih { get; set; }

    public bool enabled { get; set; }
}