// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class AdminUser
{
    public int Id { get; set; }

    public int adminType { get; set; }

    public int roleId { get; set; }

    public int? adminUserGroupId { get; set; }

    public int? helpDeskRoleId { get; set; }

    public int companyId { get; set; }

    public int dataOrder { get; set; }

    public string name { get; set; }

    public string shortDescription { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public string belgeNo { get; set; }

    public string perNo { get; set; }

    public string email { get; set; }

    public string imageUrl { get; set; }

    public string sapUser { get; set; }

    public string phone { get; set; }

    public string mobile { get; set; }

    public string documentUserId { get; set; }

    public string merni { get; set; }

    public string mandt { get; set; }

    public string pernr { get; set; }

    public string ename { get; set; }

    public string werks { get; set; }

    public string name1 { get; set; }

    public string btrtl { get; set; }

    public string btext { get; set; }

    public string persg { get; set; }

    public string pgtxt { get; set; }

    public string persk { get; set; }

    public string pktxt { get; set; }

    public string orgeh { get; set; }

    public string orgtx { get; set; }

    public string plans { get; set; }

    public string plstx { get; set; }

    public string stell { get; set; }

    public string stltx { get; set; }

    public string kostl { get; set; }

    public string cinsy { get; set; }

    public string sstxt { get; set; }

    public string waers { get; set; }

    public string schem { get; set; }

    public string bankl { get; set; }

    public string bankn { get; set; }

    public string iban { get; set; }

    public string slstext { get; set; }

    public string kidem { get; set; }

    public DateTime? eindt { get; set; }

    public DateTime? bdate { get; set; }

    public DateTime? fredk { get; set; }

    public string bldgr { get; set; }

    public string mrsta { get; set; }

    public string numch { get; set; }

    public string brpcl { get; set; }

    public string adrfr { get; set; }

    public string stat2 { get; set; }

    public string statx { get; set; }

    public int? departmanId { get; set; }

    public int? manager1 { get; set; }

    public int? manager2 { get; set; }

    public int? manager3 { get; set; }

    public int? manager4 { get; set; }

    public int? hremployer1 { get; set; }

    public int? hremployer2 { get; set; }

    public int? calisanTuruId { get; set; }

    public int? hrmanager { get; set; }

    public int? hrmanager1 { get; set; }

    public int? hrvekalet1 { get; set; }

    public int? hrmanager2 { get; set; }

    public int? hrvekalet2 { get; set; }

    public int? hrmanager3 { get; set; }

    public int? hrvekalet3 { get; set; }

    public int? hrmanager4 { get; set; }

    public int? hrvekalet4 { get; set; }

    public int? hrmanager5 { get; set; }

    public int? hrvekalet5 { get; set; }

    public bool? hrchanger1 { get; set; }

    public bool? hrchanger2 { get; set; }

    public bool? hrchanger3 { get; set; }

    public bool? hrchanger4 { get; set; }

    public bool? hrchanger5 { get; set; }

    public int? sectionId { get; set; }

    public bool approval { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public int? izinOnayId { get; set; }

    public string bank { get; set; }

    public int? aracOnayId { get; set; }

    public virtual ICollection<ActionLog> ActionLog { get; set; } = new List<ActionLog>();

    public virtual ICollection<ActivePaymentDetail> ActivePaymentDetailuser { get; set; } = new List<ActivePaymentDetail>();

    public virtual ICollection<ActivePaymentDetail> ActivePaymentDetailvekalet { get; set; } = new List<ActivePaymentDetail>();

    public virtual ICollection<ActiveProcessDetail> ActiveProcessDetailuser { get; set; } = new List<ActiveProcessDetail>();

    public virtual ICollection<ActiveProcessDetail> ActiveProcessDetailvekalet { get; set; } = new List<ActiveProcessDetail>();

    public virtual ICollection<ActiveProcess> ActiveProcesscreatedUser { get; set; } = new List<ActiveProcess>();

    public virtual ICollection<ActiveProcess> ActiveProcesscurrentUser { get; set; } = new List<ActiveProcess>();

    public virtual ICollection<ActiveProcess> ActiveProcessuserVekalet { get; set; } = new List<ActiveProcess>();

    public virtual ICollection<ActiveTransferDetail> ActiveTransferDetailuser { get; set; } = new List<ActiveTransferDetail>();

    public virtual ICollection<ActiveTransferDetail> ActiveTransferDetailvekalet { get; set; } = new List<ActiveTransferDetail>();

    public virtual ICollection<Announcement> Announcement { get; set; } = new List<Announcement>();

    public virtual ICollection<AnnualLeaveDetail> AnnualLeaveDetailuser { get; set; } = new List<AnnualLeaveDetail>();

    public virtual ICollection<AnnualLeaveDetail> AnnualLeaveDetailvekaletUser { get; set; } = new List<AnnualLeaveDetail>();

    public virtual ICollection<AnnualLeaveTable> AnnualLeaveTablecurrentUser { get; set; } = new List<AnnualLeaveTable>();

    public virtual ICollection<AnnualLeaveTable> AnnualLeaveTableuser { get; set; } = new List<AnnualLeaveTable>();

    public virtual ICollection<AnnualLeaveTable> AnnualLeaveTablevekalet { get; set; } = new List<AnnualLeaveTable>();

    public virtual ICollection<ApprovalProcessDetail> ApprovalProcessDetailuser { get; set; } = new List<ApprovalProcessDetail>();

    public virtual ICollection<ApprovalProcessDetail> ApprovalProcessDetailvekalet { get; set; } = new List<ApprovalProcessDetail>();

    public virtual ICollection<AracTalepTable> AracTalepTable { get; set; } = new List<AracTalepTable>();

    public virtual ICollection<AracTalepTableDetail> AracTalepTableDetail { get; set; } = new List<AracTalepTableDetail>();

    public virtual ICollection<AttachedFile> AttachedFile { get; set; } = new List<AttachedFile>();

    public virtual ICollection<AuditorTable> AuditorTable { get; set; } = new List<AuditorTable>();

    public virtual ICollection<BolumUserHierarchyTable> BolumUserHierarchyTablemanager { get; set; } = new List<BolumUserHierarchyTable>();

    public virtual ICollection<BolumUserHierarchyTable> BolumUserHierarchyTableuser { get; set; } = new List<BolumUserHierarchyTable>();

    public virtual ICollection<CeoTable> CeoTable { get; set; } = new List<CeoTable>();

    public virtual ICollection<CompanyYetkili> CompanyYetkili { get; set; } = new List<CompanyYetkili>();

    public virtual ICollection<DahiliYazismaMessage> DahiliYazismaMessagesendUser { get; set; } = new List<DahiliYazismaMessage>();

    public virtual ICollection<DahiliYazismaMessage> DahiliYazismaMessageuser { get; set; } = new List<DahiliYazismaMessage>();

    public virtual ICollection<DahiliYazismaTable> DahiliYazismaTablebirimAmiri { get; set; } = new List<DahiliYazismaTable>();

    public virtual ICollection<DahiliYazismaTable> DahiliYazismaTablecreatedUser { get; set; } = new List<DahiliYazismaTable>();

    public virtual ICollection<DahiliYazismalarDetayTable> DahiliYazismalarDetayTable { get; set; } = new List<DahiliYazismalarDetayTable>();

    public virtual ICollection<EgitimBolumTable> EgitimBolumTable { get; set; } = new List<EgitimBolumTable>();

    public virtual ICollection<EgitimSoruCevap> EgitimSoruCevap { get; set; } = new List<EgitimSoruCevap>();

    public virtual ICollection<EgitimSoruCevap_2022> EgitimSoruCevap_2022 { get; set; } = new List<EgitimSoruCevap_2022>();

    public virtual ICollection<EgitimSorulariTable> EgitimSorulariTable { get; set; } = new List<EgitimSorulariTable>();

    public virtual ICollection<EgitimTable> EgitimTable { get; set; } = new List<EgitimTable>();

    public virtual ICollection<EgitimVideoIzlemeTable> EgitimVideoIzlemeTable { get; set; } = new List<EgitimVideoIzlemeTable>();

    public virtual ICollection<EgitimVideoIzlemeTable_2022> EgitimVideoIzlemeTable_2022 { get; set; } = new List<EgitimVideoIzlemeTable_2022>();

    public virtual ICollection<EgitimVideoTable> EgitimVideoTable { get; set; } = new List<EgitimVideoTable>();

    public virtual ICollection<FinansUserTable> FinansUserTable { get; set; } = new List<FinansUserTable>();

    public virtual ICollection<HRAnnouncement> HRAnnouncement { get; set; } = new List<HRAnnouncement>();

    public virtual ICollection<HRAnnualSapIntegration> HRAnnualSapIntegration { get; set; } = new List<HRAnnualSapIntegration>();

    public virtual ICollection<HRExpenseDetail> HRExpenseDetailuser { get; set; } = new List<HRExpenseDetail>();

    public virtual ICollection<HRExpenseDetail> HRExpenseDetailvekaletUser { get; set; } = new List<HRExpenseDetail>();

    public virtual ICollection<HRExpenseTable> HRExpenseTablecreatedUser { get; set; } = new List<HRExpenseTable>();

    public virtual ICollection<HRExpenseTable> HRExpenseTablecurrentUser { get; set; } = new List<HRExpenseTable>();

    public virtual ICollection<HRExpenseTripDetail> HRExpenseTripDetail { get; set; } = new List<HRExpenseTripDetail>();

    public virtual ICollection<HRExpenseTripTable> HRExpenseTripTablecreatedUser { get; set; } = new List<HRExpenseTripTable>();

    public virtual ICollection<HRExpenseTripTable> HRExpenseTripTablecurrentUser { get; set; } = new List<HRExpenseTripTable>();

    public virtual ICollection<HRExpenseTripTable> HRExpenseTripTableuser { get; set; } = new List<HRExpenseTripTable>();

    public virtual ICollection<HRExpenseWithOutDetail> HRExpenseWithOutDetailuser { get; set; } = new List<HRExpenseWithOutDetail>();

    public virtual ICollection<HRExpenseWithOutDetail> HRExpenseWithOutDetailvekaletUser { get; set; } = new List<HRExpenseWithOutDetail>();

    public virtual ICollection<HRExpenseWithOutTable> HRExpenseWithOutTablecreatedUser { get; set; } = new List<HRExpenseWithOutTable>();

    public virtual ICollection<HRExpenseWithOutTable> HRExpenseWithOutTablecurrentUser { get; set; } = new List<HRExpenseWithOutTable>();

    public virtual ICollection<HRExpenseWithOutTripTable> HRExpenseWithOutTripTablecreatedUser { get; set; } = new List<HRExpenseWithOutTripTable>();

    public virtual ICollection<HRExpenseWithOutTripTable> HRExpenseWithOutTripTableuser { get; set; } = new List<HRExpenseWithOutTripTable>();

    public virtual ICollection<HRMuhasebecilerTable> HRMuhasebecilerTable { get; set; } = new List<HRMuhasebecilerTable>();

    public virtual ICollection<HRUserLog> HRUserLogchangedUser { get; set; } = new List<HRUserLog>();

    public virtual ICollection<HRUserLog> HRUserLogchangingUser { get; set; } = new List<HRUserLog>();

    public virtual ICollection<HRUserLog> HRUserLoguser { get; set; } = new List<HRUserLog>();

    public virtual ICollection<HRVekaletTable> HRVekaletTablevekaletAlan { get; set; } = new List<HRVekaletTable>();

    public virtual ICollection<HRVekaletTable> HRVekaletTablevekaletVeren { get; set; } = new List<HRVekaletTable>();

    public virtual ICollection<HelpDeskDemand> HelpDeskDemand { get; set; } = new List<HelpDeskDemand>();

    public virtual ICollection<HelpDeskDemandHistory> HelpDeskDemandHistory { get; set; } = new List<HelpDeskDemandHistory>();

    public virtual ICollection<HelpDeskMessage> HelpDeskMessage { get; set; } = new List<HelpDeskMessage>();

    public virtual ICollection<ISGAksiyonTable> ISGAksiyonTable { get; set; } = new List<ISGAksiyonTable>();

    public virtual ICollection<ISGGunTable> ISGGunTable { get; set; } = new List<ISGGunTable>();

    public virtual ICollection<ISGUser> ISGUser { get; set; } = new List<ISGUser>();

    public virtual ICollection<IncomingDocument> IncomingDocument { get; set; } = new List<IncomingDocument>();

    public virtual ICollection<AdminUser> Inversehremployer1Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversehremployer2Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversehrvekalet1Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversehrvekalet2Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversehrvekalet3Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversehrvekalet4Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversehrvekalet5Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversemanager1Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversemanager2Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversemanager3Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> Inversemanager4Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<MusteriSikayetAction> MusteriSikayetAction { get; set; } = new List<MusteriSikayetAction>();

    public virtual ICollection<MusteriSikayetAksiyonTipi> MusteriSikayetAksiyonTipi { get; set; } = new List<MusteriSikayetAksiyonTipi>();

    public virtual ICollection<MusteriSikayetCategory> MusteriSikayetCategory { get; set; } = new List<MusteriSikayetCategory>();

    public virtual ICollection<MusteriSikayetEmail> MusteriSikayetEmailcreatedUser { get; set; } = new List<MusteriSikayetEmail>();

    public virtual ICollection<MusteriSikayetEmail> MusteriSikayetEmailuser { get; set; } = new List<MusteriSikayetEmail>();

    public virtual ICollection<MusteriSikayetForm> MusteriSikayetForm { get; set; } = new List<MusteriSikayetForm>();

    public virtual ICollection<MusteriSikayetKapatma> MusteriSikayetKapatmacreatedUser { get; set; } = new List<MusteriSikayetKapatma>();

    public virtual ICollection<MusteriSikayetKapatma> MusteriSikayetKapatmadirector { get; set; } = new List<MusteriSikayetKapatma>();

    public virtual ICollection<MusteriSikayetTipi> MusteriSikayetTipi { get; set; } = new List<MusteriSikayetTipi>();

    public virtual ICollection<Note> Note { get; set; } = new List<Note>();

    public virtual ICollection<PressAnnouncement> PressAnnouncement { get; set; } = new List<PressAnnouncement>();

    public virtual ICollection<RatingQuestionVote> RatingQuestionVote { get; set; } = new List<RatingQuestionVote>();

    public virtual ICollection<RepresentativeExpenseDetail> RepresentativeExpenseDetail { get; set; } = new List<RepresentativeExpenseDetail>();

    public virtual ICollection<RepresentativeExpenseTable> RepresentativeExpenseTablecurrentUser { get; set; } = new List<RepresentativeExpenseTable>();

    public virtual ICollection<RepresentativeExpenseTable> RepresentativeExpenseTableuser { get; set; } = new List<RepresentativeExpenseTable>();

    public virtual ICollection<SevkiyatPlaka> SevkiyatPlaka { get; set; } = new List<SevkiyatPlaka>();

    public virtual ICollection<SozlesmeMailTable> SozlesmeMailTable { get; set; } = new List<SozlesmeMailTable>();

    public virtual ICollection<SureliIsTakipTable> SureliIsTakipTable { get; set; } = new List<SureliIsTakipTable>();

    public virtual ICollection<TiklamaSayaciTable> TiklamaSayaciTable { get; set; } = new List<TiklamaSayaciTable>();

    public virtual ICollection<UserForm> UserForm { get; set; } = new List<UserForm>();

    public virtual ICollection<UserFormTemplate> UserFormTemplate { get; set; } = new List<UserFormTemplate>();

    public virtual ICollection<UserGridSetting> UserGridSetting { get; set; } = new List<UserGridSetting>();

    public virtual ICollection<UserTelephoneTable> UserTelephoneTable { get; set; } = new List<UserTelephoneTable>();

    public virtual ICollection<WallPost> WallPostfromUser { get; set; } = new List<WallPost>();

    public virtual ICollection<WallPost> WallPosttoUser { get; set; } = new List<WallPost>();

    public virtual Company company { get; set; }

    public virtual AdminUser hremployer1Navigation { get; set; }

    public virtual AdminUser hremployer2Navigation { get; set; }

    public virtual AdminUser hrvekalet1Navigation { get; set; }

    public virtual AdminUser hrvekalet2Navigation { get; set; }

    public virtual AdminUser hrvekalet3Navigation { get; set; }

    public virtual AdminUser hrvekalet4Navigation { get; set; }

    public virtual AdminUser hrvekalet5Navigation { get; set; }

    public virtual AdminUser manager1Navigation { get; set; }

    public virtual AdminUser manager2Navigation { get; set; }

    public virtual AdminUser manager3Navigation { get; set; }

    public virtual AdminUser manager4Navigation { get; set; }

    public virtual Role role { get; set; }
}