// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class AnnualLeaveType
{
    public int Id { get; set; }

    public string typeName { get; set; }

    public string typeNameEn { get; set; }

    public string sapCode { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<AnnualLeaveTable> AnnualLeaveTable { get; set; } = new List<AnnualLeaveTable>();
}