// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class AnnualLeaveTable
{
    public int Id { get; set; }

    public int currentStateId { get; set; }

    public int currentUserId { get; set; }

    public int userId { get; set; }

    public DateTime enteredDate { get; set; }

    public string departmanName { get; set; }

    public string job { get; set; }

    public int typeId { get; set; }

    public decimal dayleft { get; set; }

    public decimal dayRequested { get; set; }

    public DateTime startDate { get; set; }

    public DateTime endDate { get; set; }

    public string adress { get; set; }

    public int? vekaletId { get; set; }

    public int siraNo { get; set; }

    public string disaprovecondition { get; set; }

    public string digerAciklama { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }


    public virtual ICollection<AnnualLeaveDetail> AnnualLeaveDetail { get; set; } = new List<AnnualLeaveDetail>();

    public virtual ICollection<HRAnnualSapIntegration> HRAnnualSapIntegration { get; set; } = new List<HRAnnualSapIntegration>();

    public virtual AdminUser currentUser { get; set; }

    public virtual AnnualLeaveType typeNavigation { get; set; }

    public virtual AdminUser user { get; set; }

    public virtual AdminUser vekalet { get; set; }
}