// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class ApprovalProcess
{
    public int Id { get; set; }

    public int companyId { get; set; }

    public int typeId { get; set; }

    public string dagitimKanali { get; set; }

    public string description { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<ActiveProcess> ActiveProcess { get; set; } = new List<ActiveProcess>();

    public virtual ICollection<ApprovalProcessDetail> ApprovalProcessDetail { get; set; } = new List<ApprovalProcessDetail>();

    public virtual Company company { get; set; }

    public virtual ApprovalProcessType type { get; set; }
}