// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class AracTuruTable
{
    public int Id { get; set; }

    public string AracTuru { get; set; }

    public bool status { get; set; }
}