// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class BolumUserHierarchyTable
{
    public int Id { get; set; }

    public string bolumAdi { get; set; }

    public int userId { get; set; }

    public int managerId { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<DahiliYazismaTable> DahiliYazismaTable { get; set; } = new List<DahiliYazismaTable>();

    public virtual AdminUser manager { get; set; }

    public virtual AdminUser user { get; set; }
}