// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class Company
{
    public int Id { get; set; }

    public string mandt { get; set; }

    public string spras { get; set; }

    public string vkorg { get; set; }

    public string vtext { get; set; }

    public string companySection { get; set; }

    public string imgUrl { get; set; }

    public string companyTitle { get; set; }

    public string companyLongName { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public string companyShortName { get; set; }

    public int? companySectionId { get; set; }

    public virtual ICollection<AdminUser> AdminUser { get; set; } = new List<AdminUser>();

    public virtual ICollection<ApprovalProcess> ApprovalProcess { get; set; } = new List<ApprovalProcess>();

    public virtual ICollection<CompanyYetkili> CompanyYetkili { get; set; } = new List<CompanyYetkili>();

    public virtual ICollection<DahiliYazismaTable> DahiliYazismaTable { get; set; } = new List<DahiliYazismaTable>();

    public virtual ICollection<EgitimBolumTable> EgitimBolumTable { get; set; } = new List<EgitimBolumTable>();

    public virtual ICollection<EnerjiPiyasasiBolumlerTable> EnerjiPiyasasiBolumlerTable { get; set; } = new List<EnerjiPiyasasiBolumlerTable>();

    public virtual ICollection<EnerjiPiyasasiFiiliTable> EnerjiPiyasasiFiiliTable { get; set; } = new List<EnerjiPiyasasiFiiliTable>();

    public virtual ICollection<EnerjiPiyasasiVeriTable> EnerjiPiyasasiVeriTable { get; set; } = new List<EnerjiPiyasasiVeriTable>();

    public virtual ICollection<FinansUserTable> FinansUserTable { get; set; } = new List<FinansUserTable>();

    public virtual ICollection<HRMuhasebecilerTable> HRMuhasebecilerTable { get; set; } = new List<HRMuhasebecilerTable>();

    public virtual ICollection<HelpDeskDemand> HelpDeskDemand { get; set; } = new List<HelpDeskDemand>();

    public virtual ICollection<ISGAksiyonTable> ISGAksiyonTable { get; set; } = new List<ISGAksiyonTable>();

    public virtual ICollection<ISGGunTable> ISGGunTable { get; set; } = new List<ISGGunTable>();

    public virtual ICollection<ISGUser> ISGUser { get; set; } = new List<ISGUser>();

    public virtual ICollection<IncomingDocument> IncomingDocument { get; set; } = new List<IncomingDocument>();

    public virtual ICollection<MusteriSikayetAction> MusteriSikayetAction { get; set; } = new List<MusteriSikayetAction>();

    public virtual ICollection<MusteriSikayetForm> MusteriSikayetForm { get; set; } = new List<MusteriSikayetForm>();

    public virtual ICollection<MusteriSikayetKapatma> MusteriSikayetKapatma { get; set; } = new List<MusteriSikayetKapatma>();

    public virtual ICollection<SaticiFirmalarTable> SaticiFirmalarTable { get; set; } = new List<SaticiFirmalarTable>();

    public virtual ICollection<SectionTable> SectionTable { get; set; } = new List<SectionTable>();

    public virtual ICollection<SozlesmeTable> SozlesmeTable { get; set; } = new List<SozlesmeTable>();

    public virtual ICollection<SozlesmeUpdateSatici> SozlesmeUpdateSatici { get; set; } = new List<SozlesmeUpdateSatici>();

    public virtual ICollection<SureliIsTakipTable> SureliIsTakipTable { get; set; } = new List<SureliIsTakipTable>();
}