// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string kunnr { get; set; }

    public string land1 { get; set; }

    public string name1 { get; set; }

    public string name2 { get; set; }

    public string stras { get; set; }

    public string ort01 { get; set; }

    public string pstlz { get; set; }

    public string regio { get; set; }

    public string stcd1 { get; set; }

    public string stcd2 { get; set; }

    public string telf1 { get; set; }

    public string telf2 { get; set; }

    public string telfx { get; set; }

    public string adrnr { get; set; }

    public DateTime? erdat { get; set; }

    public string ernam { get; set; }

    public string ktokd { get; set; }

    public string lifnr { get; set; }

    public string sperr { get; set; }

    public string spras { get; set; }

    public string sortl { get; set; }

    public string duefl { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }
}