// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class DahiliYazismaMessage
{
    public int Id { get; set; }

    public int dahiliYazismaId { get; set; }

    public int userId { get; set; }

    public int? sendUserId { get; set; }

    public string message { get; set; }

    public DateTime createdDate { get; set; }

    public bool showAll { get; set; }

    public bool enabled { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual DahiliYazismaTable dahiliYazisma { get; set; }

    public virtual AdminUser sendUser { get; set; }

    public virtual AdminUser user { get; set; }
}