// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class EgitimVideoIzlemeTable
{
    public int Id { get; set; }

    public int userId { get; set; }

    public int videoId { get; set; }

    public int videoSec { get; set; }

    public bool bittiMi { get; set; }

    public DateTime? izlemeTarihi { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual AdminUser user { get; set; }

    public virtual EgitimVideoTable video { get; set; }
}