// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class EgitimVideoTable
{
    public int Id { get; set; }

    public string videoName { get; set; }

    public int courseId { get; set; }

    public string videoPath { get; set; }

    public int videoOrder { get; set; }

    public int createdUserId { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public string imagePath { get; set; }

    public virtual ICollection<EgitimSorulariTable> EgitimSorulariTable { get; set; } = new List<EgitimSorulariTable>();

    public virtual ICollection<EgitimVideoIzlemeTable> EgitimVideoIzlemeTable { get; set; } = new List<EgitimVideoIzlemeTable>();

    public virtual ICollection<EgitimVideoIzlemeTable_2022> EgitimVideoIzlemeTable_2022 { get; set; } = new List<EgitimVideoIzlemeTable_2022>();

    public virtual EgitimTable course { get; set; }

    public virtual AdminUser createdUser { get; set; }
}