// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class EgitimTable
{
    public int Id { get; set; }

    public int egitimBolumId { get; set; }

    public string courseName { get; set; }

    public DateTime? startDate { get; set; }

    public DateTime? endDate { get; set; }

    public int createdUserId { get; set; }

    public DateTime createdDate { get; set; }

    public int sira { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<EgitimVideoTable> EgitimVideoTable { get; set; } = new List<EgitimVideoTable>();

    public virtual AdminUser createdUser { get; set; }

    public virtual EgitimBolumTable egitimBolum { get; set; }
}