// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class EgitimSorulariTable
{
    public int Id { get; set; }

    public int videoId { get; set; }

    public TimeSpan showVideoTime { get; set; }

    public string soru { get; set; }

    public string sikA { get; set; }

    public string sikB { get; set; }

    public string sikC { get; set; }

    public string sikD { get; set; }

    public string sikE { get; set; }

    public string dogruCevap { get; set; }

    public bool sonSoruMu { get; set; }

    public int userId { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public int? createdUserId { get; set; }

    public virtual ICollection<EgitimSoruCevap> EgitimSoruCevap { get; set; } = new List<EgitimSoruCevap>();

    public virtual ICollection<EgitimSoruCevap_2022> EgitimSoruCevap_2022 { get; set; } = new List<EgitimSoruCevap_2022>();

    public virtual AdminUser user { get; set; }

    public virtual EgitimVideoTable video { get; set; }
}