// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class EgitimBolumTable
{
    public int Id { get; set; }

    public int fabrikaId { get; set; }

    public string egitimBolumu { get; set; }

    public int sira { get; set; }

    public int createdUserId { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<EgitimTable> EgitimTable { get; set; } = new List<EgitimTable>();

    public virtual AdminUser createdUser { get; set; }

    public virtual Company fabrika { get; set; }
}