// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class EgitimSoruCevap_2022
{
    public int Id { get; set; }

    public int userId { get; set; }

    public int soruId { get; set; }

    public string cevap { get; set; }

    public DateTime? createdDate { get; set; }

    public bool enabled { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual EgitimSorulariTable soru { get; set; }

    public virtual AdminUser user { get; set; }
}