// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class EmailMessageKurumsal
{
    public int Id { get; set; }

    public int? meetingDetailId { get; set; }

    public string toAddress { get; set; }

    public string subject { get; set; }

    public string emailText { get; set; }

    public DateTime plannedDate { get; set; }

    public bool isSent { get; set; }

    public string dosya { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual MeetingDetail meetingDetail { get; set; }
}