// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class EnerjiPiyasasiVeriTable
{
    public int Id { get; set; }

    public int companyId { get; set; }

    public int bolumId { get; set; }

    public DateTime date { get; set; }

    public decimal bolum00 { get; set; }

    public decimal bolum01 { get; set; }

    public decimal bolum02 { get; set; }

    public decimal bolum03 { get; set; }

    public decimal bolum04 { get; set; }

    public decimal bolum05 { get; set; }

    public decimal bolum06 { get; set; }

    public decimal bolum07 { get; set; }

    public decimal bolum08 { get; set; }

    public decimal bolum09 { get; set; }

    public decimal bolum10 { get; set; }

    public decimal bolum11 { get; set; }

    public decimal bolum12 { get; set; }

    public decimal bolum13 { get; set; }

    public decimal bolum14 { get; set; }

    public decimal bolum15 { get; set; }

    public decimal bolum16 { get; set; }

    public decimal bolum17 { get; set; }

    public decimal bolum18 { get; set; }

    public decimal bolum19 { get; set; }

    public decimal bolum20 { get; set; }

    public decimal bolum21 { get; set; }

    public decimal bolum22 { get; set; }

    public decimal bolum23 { get; set; }

    public decimal fiili { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual EnerjiPiyasasiBolumlerTable bolum { get; set; }

    public virtual Company company { get; set; }
}