// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class EnerjiPiyasasiFiiliTable
{
    public int Id { get; set; }

    public int companyId { get; set; }

    public DateTime date { get; set; }

    public decimal saat00 { get; set; }

    public decimal saat01 { get; set; }

    public decimal saat02 { get; set; }

    public decimal saat03 { get; set; }

    public decimal saat04 { get; set; }

    public decimal saat05 { get; set; }

    public decimal saat06 { get; set; }

    public decimal saat07 { get; set; }

    public decimal saat08 { get; set; }

    public decimal saat09 { get; set; }

    public decimal saat10 { get; set; }

    public decimal saat11 { get; set; }

    public decimal saat12 { get; set; }

    public decimal saat13 { get; set; }

    public decimal saat14 { get; set; }

    public decimal saat15 { get; set; }

    public decimal saat16 { get; set; }

    public decimal saat17 { get; set; }

    public decimal saat18 { get; set; }

    public decimal saat19 { get; set; }

    public decimal saat20 { get; set; }

    public decimal saat21 { get; set; }

    public decimal saat22 { get; set; }

    public decimal saat23 { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual Company company { get; set; }
}