// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class FuelPriceDifferenceDetail
{
    public int Id { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public bool? approved { get; set; }

    public int? fuelId { get; set; }

    public Guid guid { get; set; }

    public bool? isReplied { get; set; }

    public DateTime? replyDate { get; set; }

    public int? userId { get; set; }
}