// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HelpDeskDemandRule
{
    public int Id { get; set; }

    public string companies { get; set; }

    public string helpDeskCategories { get; set; }

    public int helpDeskRoleId { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual HelpDeskRole helpDeskRole { get; set; }
}