// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HelpDeskDemand
{
    public int Id { get; set; }

    public string ticketNumber { get; set; }

    public int helpDeskTypeId { get; set; }

    public int helpDeskStatusId { get; set; }

    public int helpDeskCategoryId { get; set; }

    public int createdUserId { get; set; }

    public int createdByCompanyId { get; set; }

    public string createdByUserName { get; set; }

    public string notificationMails { get; set; }

    public int? assignedToHelpDeskRoleId { get; set; }

    public string internalNumber { get; set; }

    public string teamviewerId { get; set; }

    public string teamviewerPassword { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public string timeSpent { get; set; }

    public DateTime createdDate { get; set; }

    public bool isClosed { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<HelpDeskDemandHistory> HelpDeskDemandHistory { get; set; } = new List<HelpDeskDemandHistory>();

    public virtual ICollection<HelpDeskMessage> HelpDeskMessage { get; set; } = new List<HelpDeskMessage>();

    public virtual HelpDeskRole assignedToHelpDeskRole { get; set; }

    public virtual Company createdByCompany { get; set; }

    public virtual AdminUser createdUser { get; set; }

    public virtual HelpDeskCategory helpDeskCategory { get; set; }

    public virtual HelpDeskStatus helpDeskStatus { get; set; }

    public virtual HelpDeskType helpDeskType { get; set; }
}