// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HelpDeskCategory
{
    public int Id { get; set; }

    public int topId { get; set; }

    public string title { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<HelpDeskDemand> HelpDeskDemand { get; set; } = new List<HelpDeskDemand>();

    public virtual ICollection<HelpDeskDemandHistory> HelpDeskDemandHistory { get; set; } = new List<HelpDeskDemandHistory>();
}