// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HelpDeskDemandHistory
{
    public int Id { get; set; }

    public int helpDeskDemandId { get; set; }

    public int helpDeskStatusId { get; set; }

    public int helpDeskCategoryId { get; set; }

    public int createdUserId { get; set; }

    public string createdByUserName { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual AdminUser createdUser { get; set; }

    public virtual HelpDeskCategory helpDeskCategory { get; set; }

    public virtual HelpDeskDemand helpDeskDemand { get; set; }

    public virtual HelpDeskStatus helpDeskStatus { get; set; }
}