// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HRDestinationLocationTable
{
    public int Id { get; set; }

    public string destinationLocation { get; set; }

    public int geziYeriId { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<AracTalepTable> AracTalepTable { get; set; } = new List<AracTalepTable>();

    public virtual ICollection<HRExpenseTripTable> HRExpenseTripTabledestinationLocation { get; set; } = new List<HRExpenseTripTable>();

    public virtual ICollection<HRExpenseTripTable> HRExpenseTripTablehereLocation { get; set; } = new List<HRExpenseTripTable>();

    public virtual ICollection<HRExpenseWithOutTripTable> HRExpenseWithOutTripTable { get; set; } = new List<HRExpenseWithOutTripTable>();

    public virtual HRGidisYeri geziYeri { get; set; }
}