// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HRExpenseWithOutTripTable
{
    public int Id { get; set; }

    public int userId { get; set; }

    public DateTime? gidisTarihi { get; set; }

    public DateTime? donusTarihi { get; set; }

    public int destinationLocationId { get; set; }

    public string digerDestination { get; set; }

    public int tripDescriptionId { get; set; }

    public string tripDesciption { get; set; }

    public int? onaySirasi { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public int createdUserId { get; set; }

    public bool? approval { get; set; }

    public bool enabled { get; set; }

    public bool? lastApproved { get; set; }

    public string tripDescription { get; set; }

    public virtual ICollection<HRExpenseWithOutDetail> HRExpenseWithOutDetail { get; set; } = new List<HRExpenseWithOutDetail>();

    public virtual ICollection<HRExpenseWithOutTable> HRExpenseWithOutTable { get; set; } = new List<HRExpenseWithOutTable>();

    public virtual AdminUser createdUser { get; set; }

    public virtual HRDestinationLocationTable destinationLocation { get; set; }

    public virtual HRTripDescription tripDescriptionNavigation { get; set; }

    public virtual AdminUser user { get; set; }
}