// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HRExpenseTripTable
{
    public int Id { get; set; }

    public int currentUserId { get; set; }

    public int currentStateId { get; set; }

    public int userId { get; set; }

    public int? vekaletId { get; set; }

    public DateTime? gidisTarihi { get; set; }

    public DateTime? donusTarihi { get; set; }

    public int destinationLocationId { get; set; }

    public string tripDescription { get; set; }

    public string digerDestination { get; set; }

    public int hereLocationId { get; set; }

    public int tripDescriptionId { get; set; }

    public decimal avans { get; set; }

    public int onaySirasi { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public int createdUserId { get; set; }

    public bool? lastApproved { get; set; }

    public string disaprovecondition { get; set; }

    public bool? approval { get; set; }

    public bool enabled { get; set; }

    public virtual ICollection<HRExpenseDetail> HRExpenseDetail { get; set; } = new List<HRExpenseDetail>();

    public virtual ICollection<HRExpenseTable> HRExpenseTable { get; set; } = new List<HRExpenseTable>();

    public virtual ICollection<HRExpenseTripDetail> HRExpenseTripDetail { get; set; } = new List<HRExpenseTripDetail>();

    public virtual AdminUser createdUser { get; set; }

    public virtual AdminUser currentUser { get; set; }

    public virtual HRDestinationLocationTable destinationLocation { get; set; }

    public virtual HRDestinationLocationTable hereLocation { get; set; }

    public virtual HRTripDescription tripDescriptionNavigation { get; set; }

    public virtual AdminUser user { get; set; }
}