// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HRExpenseAmount
{
    public int Id { get; set; }

    public int calisanTuruId { get; set; }

    public int harcamaTuruId { get; set; }

    public decimal harcirahMiktari { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public DateTime? gecerlilikTarihi { get; set; }

    public virtual HREmployeeType calisanTuru { get; set; }

    public virtual HRExpenseTypeTable harcamaTuru { get; set; }
}