// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HRExpenseTypeTable
{
    public int Id { get; set; }

    public string expenseTypeName { get; set; }

    public bool toplamaNo { get; set; }

    public bool harcamaBoyu { get; set; }

    public bool otoparkMi { get; set; }

    public string sapSide { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<HRExpenseAmount> HRExpenseAmount { get; set; } = new List<HRExpenseAmount>();

    public virtual ICollection<HRExpenseTable> HRExpenseTable { get; set; } = new List<HRExpenseTable>();

    public virtual ICollection<HRExpenseWithOutTable> HRExpenseWithOutTable { get; set; } = new List<HRExpenseWithOutTable>();
}