// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HRSgkPrim
{
    public int Id { get; set; }

    public decimal sgkIsverenPayi { get; set; }

    public decimal sgkIssizlikIsv { get; set; }

    public decimal sgkIsciPayi { get; set; }

    public decimal sgkIssizlikIsci { get; set; }

    public decimal? damgaVergisi { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }
}