// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HRTripDescription
{
    public int Id { get; set; }

    public int sapId { get; set; }

    public string tripDescription { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<HRExpenseTripTable> HRExpenseTripTable { get; set; } = new List<HRExpenseTripTable>();

    public virtual ICollection<HRExpenseWithOutTripTable> HRExpenseWithOutTripTable { get; set; } = new List<HRExpenseWithOutTripTable>();
}