// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HRUserLog
{
    public int Id { get; set; }

    public int userId { get; set; }

    public int? changedId { get; set; }

    public int? changingUserId { get; set; }

    public int? changedUserId { get; set; }

    public DateTime changeDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual AdminUser changedUser { get; set; }

    public virtual AdminUser changingUser { get; set; }

    public virtual AdminUser user { get; set; }
}