// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class HRVekaletTable
{
    public int Id { get; set; }

    public int vekaletVerenId { get; set; }

    public int vekaletAlanId { get; set; }

    public DateTime? tarih { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual AdminUser vekaletAlan { get; set; }

    public virtual AdminUser vekaletVeren { get; set; }
}