// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class ISGAksiyonTable
{
    public int Id { get; set; }

    public int companyId { get; set; }

    public int uygunsuzlukKaynagiId { get; set; }

    public DateTime? uygunsuzlukTarihi { get; set; }

    public int uygunsuzlukBulunanUniteId { get; set; }

    public int bidirimdeBulunan { get; set; }

    public string uygunsuzlukAciklama { get; set; }

    public string uygunsuzlukOneri { get; set; }

    public string fileOnceki { get; set; }

    public string fileSonraki { get; set; }

    public bool bittiMi { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<ISGAksiyonTakipTable> ISGAksiyonTakipTable { get; set; } = new List<ISGAksiyonTakipTable>();

    public virtual AdminUser bidirimdeBulunanNavigation { get; set; }

    public virtual Company company { get; set; }

    public virtual SectionTable uygunsuzlukBulunanUnite { get; set; }

    public virtual ISGUygunsuzlukKaynagiTable uygunsuzlukKaynagi { get; set; }
}