// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class ISGGunTable
{
    public int Id { get; set; }

    public int companyId { get; set; }

    public DateTime timeofoccurence { get; set; }

    public int createdUserId { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual Company company { get; set; }

    public virtual AdminUser createdUser { get; set; }
}