// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class ISGUygunsuzlukKaynagiTable
{
    public int Id { get; set; }

    public string uygunsuzlukKaynagi { get; set; }

    public bool maviYakaMi { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<ISGAksiyonTable> ISGAksiyonTable { get; set; } = new List<ISGAksiyonTable>();
}