// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class KatilimcilarTable
{
    public int KatilimcilarID { get; set; }

    public string Sirket { get; set; }

    public string Katilimcilar { get; set; }

    public string Bolumu { get; set; }

    public string Email { get; set; }

    public bool status { get; set; }
}