// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class KVKDocument
{
    public int Id { get; set; }

    public int? archiveId { get; set; }

    public Guid documentId { get; set; }

    public int topId { get; set; }

    public int typeId { get; set; }

    public string typeName { get; set; }

    public string title { get; set; }

    public string fileName { get; set; }

    public int? fileSize { get; set; }

    public int createdUserId { get; set; }

    public string createdByUserName { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }
}