// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class Meeting
{
    public int Id { get; set; }

    public string users { get; set; }

    public DateTime? meetingDate { get; set; }

    public string meetingPlace { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<FactoryManagerMeetingDetail> FactoryManagerMeetingDetail { get; set; } = new List<FactoryManagerMeetingDetail>();

    public virtual ICollection<MeetingDetail> MeetingDetail { get; set; } = new List<MeetingDetail>();
}