// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class MeetingDetail
{
    public int Id { get; set; }

    public string detailNumber { get; set; }

    public int meetingId { get; set; }

    public int? copyFromMeetingId { get; set; }

    public int? copyFromMeetingDetailId { get; set; }

    public DateTime? meetingDate { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public string users { get; set; }

    public DateTime? plannedDate { get; set; }

    public DateTime? completedDate { get; set; }

    public string completedNote { get; set; }

    public int itemStatus { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<EmailMessage> EmailMessage { get; set; } = new List<EmailMessage>();

    public virtual ICollection<EmailMessageKurumsal> EmailMessageKurumsal { get; set; } = new List<EmailMessageKurumsal>();

    public virtual ICollection<EmailMessages_12112020> EmailMessages_12112020 { get; set; } = new List<EmailMessages_12112020>();

    public virtual ICollection<SMSMessage> SMSMessage { get; set; } = new List<SMSMessage>();

    public virtual Meeting meeting { get; set; }
}