// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class Menu
{
    public int Id { get; set; }

    public int locationId { get; set; }

    public int topId { get; set; }

    public int dataOrder { get; set; }

    public string title { get; set; }

    public string link { get; set; }

    public string imageUrl { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }
}