// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class MusteriSikayetForm
{
    public int Id { get; set; }

    public int categoryId { get; set; }

    public string title { get; set; }

    public string musteriKodu { get; set; }

    public string musteriAdi { get; set; }

    public int companyId { get; set; }

    public int sikayetTipiId { get; set; }

    public string malzemeTuru { get; set; }

    public decimal? malzemeMiktari { get; set; }

    public int userId { get; set; }

    public string musteriTemsilcisi { get; set; }

    public string musteriTel { get; set; }

    public string musteriEmail { get; set; }

    public bool enabled { get; set; }

    public string description { get; set; }

    public DateTime createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<MusteriSikayetAction> MusteriSikayetAction { get; set; } = new List<MusteriSikayetAction>();

    public virtual MusteriSikayetCategory category { get; set; }

    public virtual Company company { get; set; }

    public virtual MusteriSikayetTipi sikayetTipi { get; set; }

    public virtual AdminUser user { get; set; }
}