// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class MusteriSikayetTipi
{
    public int Id { get; set; }

    public string sikayetTipi { get; set; }

    public int categoryId { get; set; }

    public int createdUserId { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<MusteriSikayetForm> MusteriSikayetForm { get; set; } = new List<MusteriSikayetForm>();

    public virtual MusteriSikayetCategory category { get; set; }

    public virtual AdminUser createdUser { get; set; }
}