// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class MusteriSikayetAction
{
    public int Id { get; set; }

    public int sikayetId { get; set; }

    public int aksiyonTipiId { get; set; }

    public string actionDescription { get; set; }

    public DateTime? actionDate { get; set; }

    public int companyId { get; set; }

    public int createdUserId { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual MusteriSikayetAksiyonTipi aksiyonTipi { get; set; }

    public virtual Company company { get; set; }

    public virtual AdminUser createdUser { get; set; }

    public virtual MusteriSikayetForm sikayet { get; set; }
}