// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class MusteriSikayetCategory
{
    public int Id { get; set; }

    public string categoryName { get; set; }

    public int createdUserId { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<MusteriSikayetEmail> MusteriSikayetEmail { get; set; } = new List<MusteriSikayetEmail>();

    public virtual ICollection<MusteriSikayetForm> MusteriSikayetForm { get; set; } = new List<MusteriSikayetForm>();

    public virtual ICollection<MusteriSikayetTipi> MusteriSikayetTipi { get; set; } = new List<MusteriSikayetTipi>();

    public virtual AdminUser createdUser { get; set; }
}