// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class MusteriSikayetAksiyonTipi
{
    public int Id { get; set; }

    public string aksiyonTipi { get; set; }

    public DateTime createdDate { get; set; }

    public int createdUserId { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<MusteriSikayetAction> MusteriSikayetAction { get; set; } = new List<MusteriSikayetAction>();

    public virtual AdminUser createdUser { get; set; }
}