// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class Note
{
    public int Id { get; set; }

    public int moduleId { get; set; }

    public int targetId { get; set; }

    public int createdUserId { get; set; }

    public string description { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual AdminUser createdUser { get; set; }
}