// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class ParaBirimiTable
{
    public int Id { get; set; }

    public string paraBirimi { get; set; }

    public string paraDuzeni { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<SozlesmeTable> SozlesmeTableodemeAvansBirimi { get; set; } = new List<SozlesmeTable>();

    public virtual ICollection<SozlesmeTable> SozlesmeTablesozlesmeTutarBirimi { get; set; } = new List<SozlesmeTable>();

    public virtual ICollection<SozlesmeTable> SozlesmeTableteminatTutariParaBirim { get; set; } = new List<SozlesmeTable>();
}