// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class RatingQuestionVote
{
    public int Id { get; set; }

    public int userId { get; set; }

    public int ratingId { get; set; }

    public int questionId { get; set; }

    public int ratingValue { get; set; }

    public string comment { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual RatingQuestion question { get; set; }

    public virtual Rating rating { get; set; }

    public virtual AdminUser user { get; set; }
}