// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class Rating
{
    public int Id { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public DateTime createdDate { get; set; }

    public bool approval { get; set; }

    public bool enabled { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<RatingQuestion> RatingQuestion { get; set; } = new List<RatingQuestion>();

    public virtual ICollection<RatingQuestionVote> RatingQuestionVote { get; set; } = new List<RatingQuestionVote>();
}