// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class RatingQuestion
{
    public int Id { get; set; }

    public int ratingId { get; set; }

    public string title { get; set; }

    public int puanGorusGosterimi { get; set; }

    public int count { get; set; }

    public decimal average { get; set; }

    public DateTime createdDate { get; set; }

    public bool approval { get; set; }

    public bool enabled { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<RatingQuestionVote> RatingQuestionVote { get; set; } = new List<RatingQuestionVote>();

    public virtual Rating rating { get; set; }
}