// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class RepresentativeExpenseTable
{
    public int Id { get; set; }

    public int userId { get; set; }

    public int currentUserId { get; set; }

    public int currentStateId { get; set; }

    public DateTime? spendingTime { get; set; }

    public int typeId { get; set; }

    public string description { get; set; }

    public decimal amount { get; set; }

    public decimal approvedAmount { get; set; }

    public bool approval { get; set; }

    public int onaySirasi { get; set; }

    public string fileNames { get; set; }

    public string disaproveCondition { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<RepresentativeExpenseDetail> RepresentativeExpenseDetail { get; set; } = new List<RepresentativeExpenseDetail>();

    public virtual AdminUser currentUser { get; set; }

    public virtual RepresentativeExpenseType type { get; set; }

    public virtual AdminUser user { get; set; }
}