// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class RoleDetail
{
    public int Id { get; set; }

    public int roleId { get; set; }

    public int moduleId { get; set; }

    public bool canSee { get; set; }

    public bool canAdd { get; set; }

    public bool canEdit { get; set; }

    public bool canDelete { get; set; }

    public bool canApprove { get; set; }

    public bool canSeeLogs { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual Role role { get; set; }
}