// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class Role
{
    public int Id { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public string companies { get; set; }

    public bool approval { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual ICollection<AdminUser> AdminUser { get; set; } = new List<AdminUser>();

    public virtual ICollection<RoleDetail> RoleDetail { get; set; } = new List<RoleDetail>();
}