// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class SureliIsTakipTable
{
    public int Id { get; set; }

    public int companyId { get; set; }

    public string isinTanimi { get; set; }

    public DateTime baslamaTarihi { get; set; }

    public DateTime terminTarihi { get; set; }

    public int mailSuresi { get; set; }

    public string takipSorumlusu { get; set; }

    public string muhattaplar { get; set; }

    public bool tamamlandi { get; set; }

    public string aciklama { get; set; }

    public int createdUserId { get; set; }

    public string mailIds { get; set; }

    public string files { get; set; }

    public bool enabled { get; set; }

    public DateTime? createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public bool? surekliMi { get; set; }

    public virtual Company company { get; set; }

    public virtual AdminUser createdUser { get; set; }
}