// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class UserTelephoneTable
{
    public int Id { get; set; }

    public DateTime? createdDate { get; set; }

    public int? createdUserId { get; set; }

    public bool enabled { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public string factoryInternal { get; set; }

    public string factoryNumber { get; set; }

    public string phoneNumber { get; set; }

    public string shortCode { get; set; }

    public int userId { get; set; }

    public bool? kvkkOnay { get; set; }

    public virtual AdminUser user { get; set; }
}