// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class VersionTable
{
    public int Id { get; set; }

    public int type { get; set; }

    public int platform { get; set; }

    public string currentVersion { get; set; }

    public bool enabled { get; set; }
}