// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.Data.Models;

public partial class WallPost
{
    public int Id { get; set; }

    public int fromUserId { get; set; }

    public string fromUserName { get; set; }

    public int? toUserId { get; set; }

    public string toUserName { get; set; }

    public string text { get; set; }

    public DateTime createdDate { get; set; }

    public bool enabled { get; set; }

    public int? createdUserId { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? updatedUserId { get; set; }

    public virtual AdminUser fromUser { get; set; }

    public virtual AdminUser toUser { get; set; }
}