// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class AccountPaymentKalemSaptable
{
    public int Id { get; set; }

    public int CurrentStateId { get; set; }

    public int CurrentUserId { get; set; }

    public string Oenum { get; set; }

    public string Posnr { get; set; }

    public string Lifnr { get; set; }

    public string Name1 { get; set; }

    public string Wrbtr { get; set; }

    public string OdemeNo { get; set; }

    public string Banks { get; set; }

    public string Bankl { get; set; }

    public string Bankn { get; set; }

    public string Banka { get; set; }

    public string Brnch { get; set; }

    public string Iban { get; set; }

    public bool? Approval { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string Aciklama { get; set; }

    public virtual ICollection<ActivePaymentDetail> ActivePaymentDetails { get; set; } = new List<ActivePaymentDetail>();

    public virtual AccountPaymentSaptable OenumNavigation { get; set; }
}