// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class AccountPaymentTable
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int AccountTypeId { get; set; }

    public string Aciklama { get; set; }

    public string AliciAdiSoyadi { get; set; }

    public string AliciBanka { get; set; }

    public string AliciHesapNo { get; set; }

    public string AliciSube { get; set; }

    public string DosyaAdi { get; set; }

    public decimal? EftTutari { get; set; }

    public string KurumHesapNo { get; set; }

    public string KurumKodu { get; set; }

    public DateOnly? OdemeTarihi { get; set; }

    public string ParaBirimi { get; set; }

    public string SubeKodu { get; set; }

    public string VergiTcNo { get; set; }
}