// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class AccountPaymentSaptable
{
    public string Oenum { get; set; }

    public string Cpudt { get; set; }

    public string Cputm { get; set; }

    public string Usnam { get; set; }

    public string Aedat { get; set; }

    public string Aeuhr { get; set; }

    public string Aenam { get; set; }

    public string Bukrs { get; set; }

    public string Hkont { get; set; }

    public string KurumKodu { get; set; }

    public string SubeKodu { get; set; }

    public string Name1 { get; set; }

    public string Unva1 { get; set; }

    public string Name2 { get; set; }

    public string Unva2 { get; set; }

    public string Bstat { get; set; }

    public string Belnr { get; set; }

    public string Gjahr { get; set; }

    public string Zsayino { get; set; }

    public string Znot { get; set; }

    public string Bankl { get; set; }

    public string Bankn { get; set; }

    public string Iban { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public int? CreatedUserId { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<AccountPaymentKalemSaptable> AccountPaymentKalemSaptables { get; set; } = new List<AccountPaymentKalemSaptable>();
}