// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class ActiveProcessCheck
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string Belnr { get; set; }

    public string Kunnr { get; set; }

    public string Name1 { get; set; }

    public string Netdt { get; set; }

    public double? Wrbtr { get; set; }

    public int? ActiveProcessId { get; set; }
}