// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class ActiveProcess
{
    public int Id { get; set; }

    public int ApprovalProcessId { get; set; }

    public int CurrentStateId { get; set; }

    public int CurrentUserId { get; set; }

    public int? UserVekaletId { get; set; }

    public string DagitimKanali { get; set; }

    public string RelatedData { get; set; }

    public string RelatedDataId { get; set; }

    public string RelatedDataDesc { get; set; }

    public string RelatedDataPrimary { get; set; }

    public string RelatedDataPrimaryId { get; set; }

    public string RelatedDataPrimaryDesc { get; set; }

    public string RelatedColumn { get; set; }

    public string DataType { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string Description { get; set; }

    public string CustomFields { get; set; }

    public int CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public string Disaprovecondition { get; set; }

    public int? OncekiArtirim { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string BelgeTutari { get; set; }

    public double? AvgDays { get; set; }

    public double? AvgVade { get; set; }

    public virtual ICollection<ActiveProcessDetail> ActiveProcessDetails { get; set; } = new List<ActiveProcessDetail>();

    public virtual ApprovalProcess ApprovalProcess { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual ProcessState CurrentState { get; set; }

    public virtual AdminUser CurrentUser { get; set; }

    public virtual AdminUser UserVekalet { get; set; }
}