// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class ActiveProcessInvoice
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string Belnr { get; set; }

    public string Bldat { get; set; }

    public string Bukrs { get; set; }

    public string Dagitimkanali { get; set; }

    public double? Dmshb { get; set; }

    public string Faedt { get; set; }

    public int? Gjahr { get; set; }

    public string Zterm { get; set; }

    public int? ActiveProcessId { get; set; }
}