// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class AdminUser
{
    public int Id { get; set; }

    public int AdminType { get; set; }

    public int RoleId { get; set; }

    public int? AdminUserGroupId { get; set; }

    public int? HelpDeskRoleId { get; set; }

    public int CompanyId { get; set; }

    public int DataOrder { get; set; }

    public string Name { get; set; }

    public string ShortDescription { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string BelgeNo { get; set; }

    public string PerNo { get; set; }

    public string Email { get; set; }

    public string ImageUrl { get; set; }

    public string SapUser { get; set; }

    public string Phone { get; set; }

    public string Mobile { get; set; }

    public string DocumentUserId { get; set; }

    public string Merni { get; set; }

    public string Mandt { get; set; }

    public string Pernr { get; set; }

    public string Ename { get; set; }

    public string Werks { get; set; }

    public string Name1 { get; set; }

    public string Btrtl { get; set; }

    public string Btext { get; set; }

    public string Persg { get; set; }

    public string Pgtxt { get; set; }

    public string Persk { get; set; }

    public string Pktxt { get; set; }

    public string Orgeh { get; set; }

    public string Orgtx { get; set; }

    public string Plans { get; set; }

    public string Plstx { get; set; }

    public string Stell { get; set; }

    public string Stltx { get; set; }

    public string Kostl { get; set; }

    public string Cinsy { get; set; }

    public string Sstxt { get; set; }

    public string Waers { get; set; }

    public string Schem { get; set; }

    public string Bankl { get; set; }

    public string Bankn { get; set; }

    public string Iban { get; set; }

    public string Slstext { get; set; }

    public string Kidem { get; set; }

    public DateOnly? Eindt { get; set; }

    public DateOnly? Bdate { get; set; }

    public DateOnly? Fredk { get; set; }

    public string Bldgr { get; set; }

    public string Mrsta { get; set; }

    public string Numch { get; set; }

    public string Brpcl { get; set; }

    public string Adrfr { get; set; }

    public string Stat2 { get; set; }

    public string Statx { get; set; }

    public int? DepartmanId { get; set; }

    public int? Manager1 { get; set; }

    public int? Manager2 { get; set; }

    public int? Manager3 { get; set; }

    public int? Manager4 { get; set; }

    public int? Hremployer1 { get; set; }

    public int? Hremployer2 { get; set; }

    public int? CalisanTuruId { get; set; }

    public int? Hrmanager { get; set; }

    public int? Hrmanager1 { get; set; }

    public int? Hrvekalet1 { get; set; }

    public int? Hrmanager2 { get; set; }

    public int? Hrvekalet2 { get; set; }

    public int? Hrmanager3 { get; set; }

    public int? Hrvekalet3 { get; set; }

    public int? Hrmanager4 { get; set; }

    public int? Hrvekalet4 { get; set; }

    public int? Hrmanager5 { get; set; }

    public int? Hrvekalet5 { get; set; }

    public bool? Hrchanger1 { get; set; }

    public bool? Hrchanger2 { get; set; }

    public bool? Hrchanger3 { get; set; }

    public bool? Hrchanger4 { get; set; }

    public bool? Hrchanger5 { get; set; }

    public int? SectionId { get; set; }

    public bool Approval { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int? IzinOnayId { get; set; }

    public string Bank { get; set; }

    public int? AracOnayId { get; set; }

    public string IzinGunleri { get; set; }

    public virtual ICollection<ActionLog> ActionLogs { get; set; } = new List<ActionLog>();

    public virtual ICollection<ActivePaymentDetail> ActivePaymentDetailUsers { get; set; } = new List<ActivePaymentDetail>();

    public virtual ICollection<ActivePaymentDetail> ActivePaymentDetailVekalets { get; set; } = new List<ActivePaymentDetail>();

    public virtual ICollection<ActiveProcess> ActiveProcessCreatedUsers { get; set; } = new List<ActiveProcess>();

    public virtual ICollection<ActiveProcess> ActiveProcessCurrentUsers { get; set; } = new List<ActiveProcess>();

    public virtual ICollection<ActiveProcessDetail> ActiveProcessDetailUsers { get; set; } = new List<ActiveProcessDetail>();

    public virtual ICollection<ActiveProcessDetail> ActiveProcessDetailVekalets { get; set; } = new List<ActiveProcessDetail>();

    public virtual ICollection<ActiveProcess> ActiveProcessUserVekalets { get; set; } = new List<ActiveProcess>();

    public virtual ICollection<ActiveTransferDetail> ActiveTransferDetailUsers { get; set; } = new List<ActiveTransferDetail>();

    public virtual ICollection<ActiveTransferDetail> ActiveTransferDetailVekalets { get; set; } = new List<ActiveTransferDetail>();

    public virtual ICollection<Announcement> Announcements { get; set; } = new List<Announcement>();

    public virtual ICollection<AnnualLeaveDetail> AnnualLeaveDetailUsers { get; set; } = new List<AnnualLeaveDetail>();

    public virtual ICollection<AnnualLeaveDetail> AnnualLeaveDetailVekaletUsers { get; set; } = new List<AnnualLeaveDetail>();

    public virtual ICollection<AnnualLeaveTable> AnnualLeaveTableCurrentUsers { get; set; } = new List<AnnualLeaveTable>();

    public virtual ICollection<AnnualLeaveTable> AnnualLeaveTableUsers { get; set; } = new List<AnnualLeaveTable>();

    public virtual ICollection<AnnualLeaveTable> AnnualLeaveTableVekalets { get; set; } = new List<AnnualLeaveTable>();

    public virtual ICollection<ApprovalProcessDetail> ApprovalProcessDetailUsers { get; set; } = new List<ApprovalProcessDetail>();

    public virtual ICollection<ApprovalProcessDetail> ApprovalProcessDetailVekalets { get; set; } = new List<ApprovalProcessDetail>();

    public virtual ICollection<AracTalepTableDetail> AracTalepTableDetails { get; set; } = new List<AracTalepTableDetail>();

    public virtual ICollection<AracTalepTable> AracTalepTables { get; set; } = new List<AracTalepTable>();

    public virtual ICollection<AttachedFile> AttachedFiles { get; set; } = new List<AttachedFile>();

    public virtual ICollection<AuditorTable> AuditorTables { get; set; } = new List<AuditorTable>();

    public virtual ICollection<AuthRefreshToken> AuthRefreshTokens { get; set; } = new List<AuthRefreshToken>();

    public virtual ICollection<BolumUserHierarchyTable> BolumUserHierarchyTableManagers { get; set; } = new List<BolumUserHierarchyTable>();

    public virtual ICollection<BolumUserHierarchyTable> BolumUserHierarchyTableUsers { get; set; } = new List<BolumUserHierarchyTable>();

    public virtual ICollection<CeoTable> CeoTables { get; set; } = new List<CeoTable>();

    public virtual Company Company { get; set; }

    public virtual ICollection<CompanyYetkili> CompanyYetkilis { get; set; } = new List<CompanyYetkili>();

    public virtual ICollection<DahiliYazismaMessage> DahiliYazismaMessageSendUsers { get; set; } = new List<DahiliYazismaMessage>();

    public virtual ICollection<DahiliYazismaMessage> DahiliYazismaMessageUsers { get; set; } = new List<DahiliYazismaMessage>();

    public virtual ICollection<DahiliYazismaTable> DahiliYazismaTableBirimAmiris { get; set; } = new List<DahiliYazismaTable>();

    public virtual ICollection<DahiliYazismaTable> DahiliYazismaTableCreatedUsers { get; set; } = new List<DahiliYazismaTable>();

    public virtual ICollection<DahiliYazismalarDetayTable> DahiliYazismalarDetayTables { get; set; } = new List<DahiliYazismalarDetayTable>();

    public virtual ICollection<EgitimBolumTable> EgitimBolumTables { get; set; } = new List<EgitimBolumTable>();

    public virtual ICollection<EgitimSoruCevap2022> EgitimSoruCevap2022s { get; set; } = new List<EgitimSoruCevap2022>();

    public virtual ICollection<EgitimSoruCevap> EgitimSoruCevaps { get; set; } = new List<EgitimSoruCevap>();

    public virtual ICollection<EgitimSorulariTable> EgitimSorulariTables { get; set; } = new List<EgitimSorulariTable>();

    public virtual ICollection<EgitimTable> EgitimTables { get; set; } = new List<EgitimTable>();

    public virtual ICollection<EgitimVideoIzlemeTable2022> EgitimVideoIzlemeTable2022s { get; set; } = new List<EgitimVideoIzlemeTable2022>();

    public virtual ICollection<EgitimVideoIzlemeTable> EgitimVideoIzlemeTables { get; set; } = new List<EgitimVideoIzlemeTable>();

    public virtual ICollection<EgitimVideoTable> EgitimVideoTables { get; set; } = new List<EgitimVideoTable>();

    public virtual ICollection<FinansUserTable> FinansUserTables { get; set; } = new List<FinansUserTable>();

    public virtual ICollection<HelpDeskDemandHistory> HelpDeskDemandHistories { get; set; } = new List<HelpDeskDemandHistory>();

    public virtual ICollection<HelpDeskDemand> HelpDeskDemands { get; set; } = new List<HelpDeskDemand>();

    public virtual ICollection<HelpDeskMessage> HelpDeskMessages { get; set; } = new List<HelpDeskMessage>();

    public virtual ICollection<Hrannouncement> Hrannouncements { get; set; } = new List<Hrannouncement>();

    public virtual ICollection<HrannualSapIntegration> HrannualSapIntegrations { get; set; } = new List<HrannualSapIntegration>();

    public virtual AdminUser Hremployer1Navigation { get; set; }

    public virtual AdminUser Hremployer2Navigation { get; set; }

    public virtual ICollection<HrexpenseDetail> HrexpenseDetailUsers { get; set; } = new List<HrexpenseDetail>();

    public virtual ICollection<HrexpenseDetail> HrexpenseDetailVekaletUsers { get; set; } = new List<HrexpenseDetail>();

    public virtual ICollection<HrexpenseTable> HrexpenseTableCreatedUsers { get; set; } = new List<HrexpenseTable>();

    public virtual ICollection<HrexpenseTable> HrexpenseTableCurrentUsers { get; set; } = new List<HrexpenseTable>();

    public virtual ICollection<HrexpenseTripDetail> HrexpenseTripDetails { get; set; } = new List<HrexpenseTripDetail>();

    public virtual ICollection<HrexpenseTripTable> HrexpenseTripTableCreatedUsers { get; set; } = new List<HrexpenseTripTable>();

    public virtual ICollection<HrexpenseTripTable> HrexpenseTripTableCurrentUsers { get; set; } = new List<HrexpenseTripTable>();

    public virtual ICollection<HrexpenseTripTable> HrexpenseTripTableUsers { get; set; } = new List<HrexpenseTripTable>();

    public virtual ICollection<HrexpenseWithOutDetail> HrexpenseWithOutDetailUsers { get; set; } = new List<HrexpenseWithOutDetail>();

    public virtual ICollection<HrexpenseWithOutDetail> HrexpenseWithOutDetailVekaletUsers { get; set; } = new List<HrexpenseWithOutDetail>();

    public virtual ICollection<HrexpenseWithOutTable> HrexpenseWithOutTableCreatedUsers { get; set; } = new List<HrexpenseWithOutTable>();

    public virtual ICollection<HrexpenseWithOutTable> HrexpenseWithOutTableCurrentUsers { get; set; } = new List<HrexpenseWithOutTable>();

    public virtual ICollection<HrexpenseWithOutTripTable> HrexpenseWithOutTripTableCreatedUsers { get; set; } = new List<HrexpenseWithOutTripTable>();

    public virtual ICollection<HrexpenseWithOutTripTable> HrexpenseWithOutTripTableUsers { get; set; } = new List<HrexpenseWithOutTripTable>();

    public virtual ICollection<HrmuhasebecilerTable> HrmuhasebecilerTables { get; set; } = new List<HrmuhasebecilerTable>();

    public virtual ICollection<HruserLog> HruserLogChangedUsers { get; set; } = new List<HruserLog>();

    public virtual ICollection<HruserLog> HruserLogChangingUsers { get; set; } = new List<HruserLog>();

    public virtual ICollection<HruserLog> HruserLogUsers { get; set; } = new List<HruserLog>();

    public virtual AdminUser Hrvekalet1Navigation { get; set; }

    public virtual AdminUser Hrvekalet2Navigation { get; set; }

    public virtual AdminUser Hrvekalet3Navigation { get; set; }

    public virtual AdminUser Hrvekalet4Navigation { get; set; }

    public virtual AdminUser Hrvekalet5Navigation { get; set; }

    public virtual ICollection<HrvekaletTable> HrvekaletTableVekaletAlans { get; set; } = new List<HrvekaletTable>();

    public virtual ICollection<HrvekaletTable> HrvekaletTableVekaletVerens { get; set; } = new List<HrvekaletTable>();

    public virtual ICollection<IncomingDocument> IncomingDocuments { get; set; } = new List<IncomingDocument>();

    public virtual ICollection<AdminUser> InverseHremployer1Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseHremployer2Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseHrvekalet1Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseHrvekalet2Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseHrvekalet3Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseHrvekalet4Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseHrvekalet5Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseManager1Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseManager2Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseManager3Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<AdminUser> InverseManager4Navigation { get; set; } = new List<AdminUser>();

    public virtual ICollection<IsgaksiyonTable> IsgaksiyonTables { get; set; } = new List<IsgaksiyonTable>();

    public virtual ICollection<IsggunTable> IsggunTables { get; set; } = new List<IsggunTable>();

    public virtual ICollection<Isguser> Isgusers { get; set; } = new List<Isguser>();

    public virtual AdminUser Manager1Navigation { get; set; }

    public virtual AdminUser Manager2Navigation { get; set; }

    public virtual AdminUser Manager3Navigation { get; set; }

    public virtual AdminUser Manager4Navigation { get; set; }

    public virtual ICollection<MusteriSikayetAction> MusteriSikayetActions { get; set; } = new List<MusteriSikayetAction>();

    public virtual ICollection<MusteriSikayetAksiyonTipi> MusteriSikayetAksiyonTipis { get; set; } = new List<MusteriSikayetAksiyonTipi>();

    public virtual ICollection<MusteriSikayetCategory> MusteriSikayetCategories { get; set; } = new List<MusteriSikayetCategory>();

    public virtual ICollection<MusteriSikayetEmail> MusteriSikayetEmailCreatedUsers { get; set; } = new List<MusteriSikayetEmail>();

    public virtual ICollection<MusteriSikayetEmail> MusteriSikayetEmailUsers { get; set; } = new List<MusteriSikayetEmail>();

    public virtual ICollection<MusteriSikayetForm> MusteriSikayetForms { get; set; } = new List<MusteriSikayetForm>();

    public virtual ICollection<MusteriSikayetKapatma> MusteriSikayetKapatmaCreatedUsers { get; set; } = new List<MusteriSikayetKapatma>();

    public virtual ICollection<MusteriSikayetKapatma> MusteriSikayetKapatmaDirectors { get; set; } = new List<MusteriSikayetKapatma>();

    public virtual ICollection<MusteriSikayetTipi> MusteriSikayetTipis { get; set; } = new List<MusteriSikayetTipi>();

    public virtual ICollection<Note> Notes { get; set; } = new List<Note>();

    public virtual ICollection<PressAnnouncement> PressAnnouncements { get; set; } = new List<PressAnnouncement>();

    public virtual ICollection<RatingQuestionVote> RatingQuestionVotes { get; set; } = new List<RatingQuestionVote>();

    public virtual ICollection<RepresentativeExpenseDetail> RepresentativeExpenseDetails { get; set; } = new List<RepresentativeExpenseDetail>();

    public virtual ICollection<RepresentativeExpenseTable> RepresentativeExpenseTableCurrentUsers { get; set; } = new List<RepresentativeExpenseTable>();

    public virtual ICollection<RepresentativeExpenseTable> RepresentativeExpenseTableUsers { get; set; } = new List<RepresentativeExpenseTable>();

    public virtual Role Role { get; set; }

    public virtual ICollection<SevkiyatPlaka> SevkiyatPlakas { get; set; } = new List<SevkiyatPlaka>();

    public virtual ICollection<SozlesmeMailTable> SozlesmeMailTables { get; set; } = new List<SozlesmeMailTable>();

    public virtual ICollection<SureliIsTakipTable> SureliIsTakipTables { get; set; } = new List<SureliIsTakipTable>();

    public virtual ICollection<TiklamaSayaciTable> TiklamaSayaciTables { get; set; } = new List<TiklamaSayaciTable>();

    public virtual ICollection<UserFormTemplate> UserFormTemplates { get; set; } = new List<UserFormTemplate>();

    public virtual ICollection<UserForm> UserForms { get; set; } = new List<UserForm>();

    public virtual ICollection<UserGridSetting> UserGridSettings { get; set; } = new List<UserGridSetting>();

    public virtual ICollection<UserTelephoneTable> UserTelephoneTables { get; set; } = new List<UserTelephoneTable>();

    public virtual ICollection<WallPost> WallPostFromUsers { get; set; } = new List<WallPost>();

    public virtual ICollection<WallPost> WallPostToUsers { get; set; } = new List<WallPost>();
}