// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class AnnualLeaveType
{
    public int Id { get; set; }

    public string TypeName { get; set; }

    public string TypeNameEn { get; set; }

    public string SapCode { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<AnnualLeaveTable> AnnualLeaveTables { get; set; } = new List<AnnualLeaveTable>();
}