// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class AnnualLeaveTable
{
    public int Id { get; set; }

    public int CurrentStateId { get; set; }

    public int CurrentUserId { get; set; }

    public int UserId { get; set; }

    public DateOnly EnteredDate { get; set; }

    public string DepartmanName { get; set; }

    public string Job { get; set; }

    public int TypeId { get; set; }

    public decimal Dayleft { get; set; }

    public decimal DayRequested { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string Adress { get; set; }

    public int? VekaletId { get; set; }

    public int SiraNo { get; set; }

    public string Disaprovecondition { get; set; }

    public string DigerAciklama { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public byte[] Type { get; set; }

    public virtual ICollection<AnnualLeaveDetail> AnnualLeaveDetails { get; set; } = new List<AnnualLeaveDetail>();

    public virtual AdminUser CurrentUser { get; set; }

    public virtual ICollection<HrannualSapIntegration> HrannualSapIntegrations { get; set; } = new List<HrannualSapIntegration>();

    public virtual AnnualLeaveType TypeNavigation { get; set; }

    public virtual AdminUser User { get; set; }

    public virtual AdminUser Vekalet { get; set; }
}