// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class ApprovalProcessDetail
{
    public int Id { get; set; }

    public int ProcessId { get; set; }

    public int UserId { get; set; }

    public decimal Deger { get; set; }

    public int? VekaletId { get; set; }

    public int DataOrder { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ApprovalProcess Process { get; set; }

    public virtual AdminUser User { get; set; }

    public virtual AdminUser Vekalet { get; set; }
}