// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class ApprovalProcess
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int TypeId { get; set; }

    public string DagitimKanali { get; set; }

    public string Description { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<ActiveProcess> ActiveProcesses { get; set; } = new List<ActiveProcess>();

    public virtual ICollection<ApprovalProcessDetail> ApprovalProcessDetails { get; set; } = new List<ApprovalProcessDetail>();

    public virtual Company Company { get; set; }

    public virtual ApprovalProcessType Type { get; set; }
}