// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class AracTalepTableDetail
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public bool? Approved { get; set; }

    public Guid Guid { get; set; }

    public bool? IsReplied { get; set; }

    public DateTime? ReplyDate { get; set; }

    public int? TalepId { get; set; }

    public int? UserId { get; set; }

    public int? VekaletUserId { get; set; }

    public virtual AdminUser User { get; set; }
}