// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class AracTalepTable
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string Aciklama { get; set; }

    public bool? Approval { get; set; }

    public DateOnly? BaslangicTarihi { get; set; }

    public int? CurrentStateId { get; set; }

    public int? CurrentUserId { get; set; }

    public int? DestinationLocationId { get; set; }

    public int? OnaySirasi { get; set; }

    public DateOnly? TeslimTarihi { get; set; }

    public string Plaka { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual HrdestinationLocationTable DestinationLocation { get; set; }
}