// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class AuthRefreshToken
{
    public long Id { get; set; }

    public int UserId { get; set; }

    public string TokenHash { get; set; }

    public string JwtId { get; set; }

    public string SessionId { get; set; }

    public string DeviceId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime ExpiresAtUtc { get; set; }

    public DateTime? UsedAtUtc { get; set; }

    public DateTime? RevokedAtUtc { get; set; }

    public string RevokedReason { get; set; }

    public string ReplacedByTokenHash { get; set; }

    public string CreatedByIp { get; set; }

    public string UserAgent { get; set; }

    public virtual AdminUser User { get; set; }
}