// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class ChatMessage
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string Content { get; set; }

    public int? IdFrom { get; set; }

    public string IdTo { get; set; }

    public string Timestamp { get; set; }

    public int? Type { get; set; }

    public int? ChatGroupId { get; set; }

    public string FileNames { get; set; }

    public bool? IsSent { get; set; }
}