// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class Company
{
    public int Id { get; set; }

    public string Mandt { get; set; }

    public string Spras { get; set; }

    public string Vkorg { get; set; }

    public string Vtext { get; set; }

    public string CompanySection { get; set; }

    public string ImgUrl { get; set; }

    public string CompanyTitle { get; set; }

    public string CompanyLongName { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string CompanyShortName { get; set; }

    public int? CompanySectionId { get; set; }

    public virtual ICollection<AdminUser> AdminUsers { get; set; } = new List<AdminUser>();

    public virtual ICollection<ApprovalProcess> ApprovalProcesses { get; set; } = new List<ApprovalProcess>();

    public virtual ICollection<CompanyYetkili> CompanyYetkilis { get; set; } = new List<CompanyYetkili>();

    public virtual ICollection<DahiliYazismaTable> DahiliYazismaTables { get; set; } = new List<DahiliYazismaTable>();

    public virtual ICollection<EgitimBolumTable> EgitimBolumTables { get; set; } = new List<EgitimBolumTable>();

    public virtual ICollection<EnerjiPiyasasiBolumlerTable> EnerjiPiyasasiBolumlerTables { get; set; } = new List<EnerjiPiyasasiBolumlerTable>();

    public virtual ICollection<EnerjiPiyasasiFiiliTable> EnerjiPiyasasiFiiliTables { get; set; } = new List<EnerjiPiyasasiFiiliTable>();

    public virtual ICollection<EnerjiPiyasasiVeriTable> EnerjiPiyasasiVeriTables { get; set; } = new List<EnerjiPiyasasiVeriTable>();

    public virtual ICollection<FinansUserTable> FinansUserTables { get; set; } = new List<FinansUserTable>();

    public virtual ICollection<HelpDeskDemand> HelpDeskDemands { get; set; } = new List<HelpDeskDemand>();

    public virtual ICollection<HrmuhasebecilerTable> HrmuhasebecilerTables { get; set; } = new List<HrmuhasebecilerTable>();

    public virtual ICollection<IncomingDocument> IncomingDocuments { get; set; } = new List<IncomingDocument>();

    public virtual ICollection<IsgaksiyonTable> IsgaksiyonTables { get; set; } = new List<IsgaksiyonTable>();

    public virtual ICollection<IsggunTable> IsggunTables { get; set; } = new List<IsggunTable>();

    public virtual ICollection<Isguser> Isgusers { get; set; } = new List<Isguser>();

    public virtual ICollection<MusteriSikayetAction> MusteriSikayetActions { get; set; } = new List<MusteriSikayetAction>();

    public virtual ICollection<MusteriSikayetForm> MusteriSikayetForms { get; set; } = new List<MusteriSikayetForm>();

    public virtual ICollection<MusteriSikayetKapatma> MusteriSikayetKapatmas { get; set; } = new List<MusteriSikayetKapatma>();

    public virtual ICollection<SaticiFirmalarTable> SaticiFirmalarTables { get; set; } = new List<SaticiFirmalarTable>();

    public virtual ICollection<SectionTable> SectionTables { get; set; } = new List<SectionTable>();

    public virtual ICollection<SozlesmeTable> SozlesmeTables { get; set; } = new List<SozlesmeTable>();

    public virtual ICollection<SozlesmeUpdateSatici> SozlesmeUpdateSaticis { get; set; } = new List<SozlesmeUpdateSatici>();

    public virtual ICollection<SureliIsTakipTable> SureliIsTakipTables { get; set; } = new List<SureliIsTakipTable>();
}