// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class Config
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Name { get; set; }

    public string AppServerHost { get; set; }

    public string SystemNumber { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Client { get; set; }

    public string Language { get; set; }

    public string PoolSize { get; set; }

    public string PeakConnectionsLimit { get; set; }

    public string IdleTimeout { get; set; }

    public string SystemId { get; set; }

    public string SapRouter { get; set; }

    public bool IsDefault { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }
}