// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string Kunnr { get; set; }

    public string Land1 { get; set; }

    public string Name1 { get; set; }

    public string Name2 { get; set; }

    public string Stras { get; set; }

    public string Ort01 { get; set; }

    public string Pstlz { get; set; }

    public string Regio { get; set; }

    public string Stcd1 { get; set; }

    public string Stcd2 { get; set; }

    public string Telf1 { get; set; }

    public string Telf2 { get; set; }

    public string Telfx { get; set; }

    public string Adrnr { get; set; }

    public DateOnly? Erdat { get; set; }

    public string Ernam { get; set; }

    public string Ktokd { get; set; }

    public string Lifnr { get; set; }

    public string Sperr { get; set; }

    public string Spras { get; set; }

    public string Sortl { get; set; }

    public string Duefl { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }
}