// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class DahiliYazismalarDetayTable
{
    public int Id { get; set; }

    public int DahiliYazismaId { get; set; }

    public int UserId { get; set; }

    public int? VekaletId { get; set; }

    public bool? Approved { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsReplied { get; set; }

    public DateTime? ReplyDate { get; set; }

    public bool KanalBittiMi { get; set; }

    public bool SonOnayMi { get; set; }

    public bool Enabled { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual DahiliYazismaTable DahiliYazisma { get; set; }

    public virtual AdminUser User { get; set; }
}