// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class DahiliYazismaTable
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public string Servisi { get; set; }

    public string Konu { get; set; }

    public DateOnly? Tarih { get; set; }

    public int? KanalId { get; set; }

    public string Icerik { get; set; }

    public string KanalGorusuCeo { get; set; }

    public string KanalGorusuFirst { get; set; }

    public string KanalGorusu { get; set; }

    public string KanalGorusuAsil { get; set; }

    public int CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? Onaylayici1 { get; set; }

    public int? Onaylayici2 { get; set; }

    public int? Onaylayici3 { get; set; }

    public int? Onaylayici4 { get; set; }

    public int? Onay1Kanal { get; set; }

    public int? KanalGorusuUserId { get; set; }

    public bool KanalGorusuOkmi { get; set; }

    public int? BilgiUserId1 { get; set; }

    public int? BilgiUserId2 { get; set; }

    public int? BilgiUserId3 { get; set; }

    public int? BilgiUserId4 { get; set; }

    public int? BilgiUserId5 { get; set; }

    public bool BilgiBittiMi { get; set; }

    public int BirimAmiriId { get; set; }

    public int? LastUserId { get; set; }

    public int? LastUserId2 { get; set; }

    public bool Onay1Ok { get; set; }

    public bool Onay2Ok { get; set; }

    public bool Onay3Ok { get; set; }

    public bool Onay4Ok { get; set; }

    public bool OnaylandiMi { get; set; }

    public string Disaprovecondition { get; set; }

    public string BackNote { get; set; }

    public string BackNoteKanal { get; set; }

    public string BackNoteMudur { get; set; }

    public string LastNote { get; set; }

    public bool MudurBittiMi { get; set; }

    public bool RedEttiMi { get; set; }

    public bool KanalBittiMi { get; set; }

    public bool BittiMi { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string Note { get; set; }

    public int? NoteUserId { get; set; }

    public virtual AdminUser BirimAmiri { get; set; }

    public virtual Company Company { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual ICollection<DahiliYazismaMessage> DahiliYazismaMessages { get; set; } = new List<DahiliYazismaMessage>();

    public virtual ICollection<DahiliYazismalarDetayTable> DahiliYazismalarDetayTables { get; set; } = new List<DahiliYazismalarDetayTable>();

    public virtual BolumUserHierarchyTable Kanal { get; set; }
}