// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class DieselPrice
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public bool? Approval { get; set; }

    public int? CompanyId { get; set; }

    public int? CurrentStateId { get; set; }

    public int? CurrentUserId { get; set; }

    public decimal Fiyat { get; set; }

    public DateOnly GirisTarihi { get; set; }

    public int KdvRate { get; set; }

    public int? OnaySirasi { get; set; }
}