// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class DigitalCoridorTable
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Location { get; set; }

    public int SectionId { get; set; }

    public string Email { get; set; }

    public string User1 { get; set; }

    public string User2 { get; set; }

    public string User3 { get; set; }

    public string User4 { get; set; }

    public string User5 { get; set; }

    public string User6 { get; set; }

    public string User7 { get; set; }

    public string User8 { get; set; }

    public string User9 { get; set; }

    public string User10 { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }
}