// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EarsivFatura
{
    public string Ettn { get; set; }

    public string BelgeNumarasi { get; set; }

    public DateOnly? BelgeTarihi { get; set; }

    public string BelgeTuru { get; set; }

    public bool BittiMi { get; set; }

    public int? CompanyId { get; set; }

    public bool? Enabled { get; set; }

    public int? IptalItiraz { get; set; }

    public string OnayDurumu { get; set; }

    public string SaticiUnvanAdSoyad { get; set; }

    public string SaticiVknTckn { get; set; }

    public int? TalepDurum { get; set; }

    public int? UserId { get; set; }

    public DateTime? PullTime { get; set; }
}