// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EducationQuestionsTable
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string DogruCevap { get; set; }

    public int? SectionId { get; set; }

    public string SikA { get; set; }

    public string SikB { get; set; }

    public string SikC { get; set; }

    public string SikD { get; set; }

    public string SikE { get; set; }

    public int? Sira { get; set; }

    public bool SonSoruMu { get; set; }

    public string Soru { get; set; }
}