// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EgitimSorulariTable
{
    public int Id { get; set; }

    public int VideoId { get; set; }

    public TimeOnly ShowVideoTime { get; set; }

    public string Soru { get; set; }

    public string SikA { get; set; }

    public string SikB { get; set; }

    public string SikC { get; set; }

    public string SikD { get; set; }

    public string SikE { get; set; }

    public string DogruCevap { get; set; }

    public bool SonSoruMu { get; set; }

    public int UserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int? CreatedUserId { get; set; }

    public virtual ICollection<EgitimSoruCevap2022> EgitimSoruCevap2022s { get; set; } = new List<EgitimSoruCevap2022>();

    public virtual ICollection<EgitimSoruCevap> EgitimSoruCevaps { get; set; } = new List<EgitimSoruCevap>();

    public virtual AdminUser User { get; set; }

    public virtual EgitimVideoTable Video { get; set; }
}