// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EgitimBolumTable
{
    public int Id { get; set; }

    public int FabrikaId { get; set; }

    public string EgitimBolumu { get; set; }

    public int Sira { get; set; }

    public int CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual ICollection<EgitimTable> EgitimTables { get; set; } = new List<EgitimTable>();

    public virtual Company Fabrika { get; set; }
}