// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EgitimTable
{
    public int Id { get; set; }

    public int EgitimBolumId { get; set; }

    public string CourseName { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int Sira { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual EgitimBolumTable EgitimBolum { get; set; }

    public virtual ICollection<EgitimVideoTable> EgitimVideoTables { get; set; } = new List<EgitimVideoTable>();
}