// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EgitimVideoTable
{
    public int Id { get; set; }

    public string VideoName { get; set; }

    public int CourseId { get; set; }

    public string VideoPath { get; set; }

    public int VideoOrder { get; set; }

    public int CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string ImagePath { get; set; }

    public virtual EgitimTable Course { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual ICollection<EgitimSorulariTable> EgitimSorulariTables { get; set; } = new List<EgitimSorulariTable>();

    public virtual ICollection<EgitimVideoIzlemeTable2022> EgitimVideoIzlemeTable2022s { get; set; } = new List<EgitimVideoIzlemeTable2022>();

    public virtual ICollection<EgitimVideoIzlemeTable> EgitimVideoIzlemeTables { get; set; } = new List<EgitimVideoIzlemeTable>();
}