// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EmailMessages12112020
{
    public int Id { get; set; }

    public int? MeetingDetailId { get; set; }

    public string ToAddress { get; set; }

    public string Subject { get; set; }

    public string EmailText { get; set; }

    public DateTime PlannedDate { get; set; }

    public bool IsSent { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual MeetingDetail MeetingDetail { get; set; }
}