// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EmailMessage
{
    public int Id { get; set; }

    public int? MeetingDetailId { get; set; }

    public string ToAddress { get; set; }

    public string Subject { get; set; }

    public string EmailText { get; set; }

    public DateTime PlannedDate { get; set; }

    public bool IsSent { get; set; }

    public int? MailTuru { get; set; }

    public string Dosya { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public bool? IsSentEmailControl { get; set; }
}