// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Merni { get; set; }

    public string Mandt { get; set; }

    public string Pernr { get; set; }

    public string Ename { get; set; }

    public string Werks { get; set; }

    public string Name1 { get; set; }

    public string Btrtl { get; set; }

    public string Btext { get; set; }

    public string Persg { get; set; }

    public string Pgtxt { get; set; }

    public string Persk { get; set; }

    public string Pktxt { get; set; }

    public string Orgeh { get; set; }

    public string Orgtx { get; set; }

    public string Plans { get; set; }

    public string Plstx { get; set; }

    public string Stell { get; set; }

    public string Stltx { get; set; }

    public string Kostl { get; set; }

    public string Cinsy { get; set; }

    public string Sstxt { get; set; }

    public string Waers { get; set; }

    public string Schem { get; set; }

    public string Bankl { get; set; }

    public string Bankn { get; set; }

    public string Iban { get; set; }

    public string Slstext { get; set; }

    public string Kidem { get; set; }

    public DateOnly? Eindt { get; set; }

    public DateOnly? Bdate { get; set; }

    public DateOnly? Fredt { get; set; }

    public string Bldgr { get; set; }

    public string Mrsta { get; set; }

    public string Numch { get; set; }

    public string Brplc { get; set; }

    public string Adrfr { get; set; }

    public string Stat2 { get; set; }

    public string Statx { get; set; }

    public string Sysuname { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public Guid? IdEmployee { get; set; }

    public int? UpdatedUserId { get; set; }
}