// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EnerjiPiyasasiVeriTable
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int BolumId { get; set; }

    public DateOnly Date { get; set; }

    public decimal Bolum00 { get; set; }

    public decimal Bolum01 { get; set; }

    public decimal Bolum02 { get; set; }

    public decimal Bolum03 { get; set; }

    public decimal Bolum04 { get; set; }

    public decimal Bolum05 { get; set; }

    public decimal Bolum06 { get; set; }

    public decimal Bolum07 { get; set; }

    public decimal Bolum08 { get; set; }

    public decimal Bolum09 { get; set; }

    public decimal Bolum10 { get; set; }

    public decimal Bolum11 { get; set; }

    public decimal Bolum12 { get; set; }

    public decimal Bolum13 { get; set; }

    public decimal Bolum14 { get; set; }

    public decimal Bolum15 { get; set; }

    public decimal Bolum16 { get; set; }

    public decimal Bolum17 { get; set; }

    public decimal Bolum18 { get; set; }

    public decimal Bolum19 { get; set; }

    public decimal Bolum20 { get; set; }

    public decimal Bolum21 { get; set; }

    public decimal Bolum22 { get; set; }

    public decimal Bolum23 { get; set; }

    public decimal Fiili { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual EnerjiPiyasasiBolumlerTable Bolum { get; set; }

    public virtual Company Company { get; set; }
}