// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EnerjiPiyasasiBolumlerTable
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public string BolumAdi { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<EnerjiPiyasasiVeriTable> EnerjiPiyasasiVeriTables { get; set; } = new List<EnerjiPiyasasiVeriTable>();
}