// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class EnerjiPiyasasiFiiliTable
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public DateOnly Date { get; set; }

    public decimal Saat00 { get; set; }

    public decimal Saat01 { get; set; }

    public decimal Saat02 { get; set; }

    public decimal Saat03 { get; set; }

    public decimal Saat04 { get; set; }

    public decimal Saat05 { get; set; }

    public decimal Saat06 { get; set; }

    public decimal Saat07 { get; set; }

    public decimal Saat08 { get; set; }

    public decimal Saat09 { get; set; }

    public decimal Saat10 { get; set; }

    public decimal Saat11 { get; set; }

    public decimal Saat12 { get; set; }

    public decimal Saat13 { get; set; }

    public decimal Saat14 { get; set; }

    public decimal Saat15 { get; set; }

    public decimal Saat16 { get; set; }

    public decimal Saat17 { get; set; }

    public decimal Saat18 { get; set; }

    public decimal Saat19 { get; set; }

    public decimal Saat20 { get; set; }

    public decimal Saat21 { get; set; }

    public decimal Saat22 { get; set; }

    public decimal Saat23 { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual Company Company { get; set; }
}