// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class FactoryManagerMeetingUser
{
    public int Id { get; set; }

    public int DataOrder { get; set; }

    public string Name { get; set; }

    public string Title { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<FactoryManagerMeetingPerformanceUser> FactoryManagerMeetingPerformanceUsers { get; set; } = new List<FactoryManagerMeetingPerformanceUser>();
}