// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class FactoryManagerMeetingDetail
{
    public int Id { get; set; }

    public string DetailNumber { get; set; }

    public int MeetingId { get; set; }

    public int? CopyFromMeetingId { get; set; }

    public int? CopyFromMeetingDetailId { get; set; }

    public DateTime? MeetingDate { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Users { get; set; }

    public DateTime? PlannedDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    public string CompletedNote { get; set; }

    public int ItemStatus { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual Meeting Meeting { get; set; }
}