// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class FuelPriceDifference
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public bool? Approval { get; set; }

    public int? BirimId { get; set; }

    public int? CompanyId { get; set; }

    public int? CurrentStateId { get; set; }

    public int? CurrentUserId { get; set; }

    public int? EditId { get; set; }

    public decimal Fiyat { get; set; }

    public DateOnly? FiyatTarih { get; set; }

    public string IsinAdi { get; set; }

    public decimal KatSayi { get; set; }

    public decimal? Km { get; set; }

    public string Nevi { get; set; }

    public int? OnaySirasi { get; set; }

    public DateOnly SozlesmeBaslangic { get; set; }

    public DateOnly SozlesmeBitis { get; set; }

    public int? UserId { get; set; }

    public string YukleniciFirma { get; set; }
}