// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HelpDeskDemandHistory
{
    public int Id { get; set; }

    public int HelpDeskDemandId { get; set; }

    public int HelpDeskStatusId { get; set; }

    public int HelpDeskCategoryId { get; set; }

    public int CreatedUserId { get; set; }

    public string CreatedByUserName { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual HelpDeskCategory HelpDeskCategory { get; set; }

    public virtual HelpDeskDemand HelpDeskDemand { get; set; }

    public virtual HelpDeskStatus HelpDeskStatus { get; set; }
}