// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HelpDeskCategory
{
    public int Id { get; set; }

    public int TopId { get; set; }

    public string Title { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<HelpDeskDemandHistory> HelpDeskDemandHistories { get; set; } = new List<HelpDeskDemandHistory>();

    public virtual ICollection<HelpDeskDemand> HelpDeskDemands { get; set; } = new List<HelpDeskDemand>();
}