// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HelpDeskDemand
{
    public int Id { get; set; }

    public string TicketNumber { get; set; }

    public int HelpDeskTypeId { get; set; }

    public int HelpDeskStatusId { get; set; }

    public int HelpDeskCategoryId { get; set; }

    public int CreatedUserId { get; set; }

    public int CreatedByCompanyId { get; set; }

    public string CreatedByUserName { get; set; }

    public string NotificationMails { get; set; }

    public int? AssignedToHelpDeskRoleId { get; set; }

    public string InternalNumber { get; set; }

    public string TeamviewerId { get; set; }

    public string TeamviewerPassword { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string TimeSpent { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsClosed { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual HelpDeskRole AssignedToHelpDeskRole { get; set; }

    public virtual Company CreatedByCompany { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual HelpDeskCategory HelpDeskCategory { get; set; }

    public virtual ICollection<HelpDeskDemandHistory> HelpDeskDemandHistories { get; set; } = new List<HelpDeskDemandHistory>();

    public virtual ICollection<HelpDeskMessage> HelpDeskMessages { get; set; } = new List<HelpDeskMessage>();

    public virtual HelpDeskStatus HelpDeskStatus { get; set; }

    public virtual HelpDeskType HelpDeskType { get; set; }
}