// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HelpDeskDemandRule
{
    public int Id { get; set; }

    public string Companies { get; set; }

    public string HelpDeskCategories { get; set; }

    public int HelpDeskRoleId { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual HelpDeskRole HelpDeskRole { get; set; }
}