// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrannualSapIntegration
{
    public int Id { get; set; }

    public string Perno { get; set; }

    public int YillikIzinId { get; set; }

    public DateTime? Izinbaslangici { get; set; }

    public DateTime? Izinbitisi { get; set; }

    public string Saat { get; set; }

    public string Duzeltme { get; set; }

    public string Izinturu { get; set; }

    public bool Approval { get; set; }

    public int UserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public bool SapControl { get; set; }

    public virtual AdminUser User { get; set; }

    public virtual AnnualLeaveTable YillikIzin { get; set; }
}