// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrdestinationLocationTable
{
    public int Id { get; set; }

    public string DestinationLocation { get; set; }

    public int GeziYeriId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<AracTalepTable> AracTalepTables { get; set; } = new List<AracTalepTable>();

    public virtual HrgidisYeri GeziYeri { get; set; }

    public virtual ICollection<HrexpenseTripTable> HrexpenseTripTableDestinationLocations { get; set; } = new List<HrexpenseTripTable>();

    public virtual ICollection<HrexpenseTripTable> HrexpenseTripTableHereLocations { get; set; } = new List<HrexpenseTripTable>();

    public virtual ICollection<HrexpenseWithOutTripTable> HrexpenseWithOutTripTables { get; set; } = new List<HrexpenseWithOutTripTable>();
}