// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class Hrdocument
{
    public int Id { get; set; }

    public int? ArchiveId { get; set; }

    public Guid DocumentId { get; set; }

    public int TopId { get; set; }

    public int TypeId { get; set; }

    public string TypeName { get; set; }

    public string Title { get; set; }

    public string FileName { get; set; }

    public int? FileSize { get; set; }

    public int CreatedUserId { get; set; }

    public string CreatedByUserName { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int? CreatedByUserId { get; set; }
}