// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrexpenseTable
{
    public int Id { get; set; }

    public int TripId { get; set; }

    public int IslemTuruId { get; set; }

    public int CurrentStateId { get; set; }

    public int CurrentUserId { get; set; }

    public int ExpenseTypeId { get; set; }

    public string Plaka { get; set; }

    public int AracTuruId { get; set; }

    public decimal Amount { get; set; }

    public decimal ApprovedAmount { get; set; }

    public decimal? TotalLimitAmount { get; set; }

    public int KalinanGunSayisi { get; set; }

    public int OtoparkGunSayisi { get; set; }

    public string KdvOrani { get; set; }

    public decimal? KdvDegeri { get; set; }

    public DateOnly? SpendingTime { get; set; }

    public string ExpenseDescription { get; set; }

    public string FileNames { get; set; }

    public int CreatedUserId { get; set; }

    public bool? Approval { get; set; }

    public bool? LastApproved { get; set; }

    public int OnaySirasi { get; set; }

    public bool GunlukMu { get; set; }

    public string HrNot { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual AdminUser CurrentUser { get; set; }

    public virtual HrexpenseTypeTable ExpenseType { get; set; }

    public virtual HrislemTuruTable IslemTuru { get; set; }

    public virtual HrexpenseTripTable Trip { get; set; }
}