// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrexpenseTripTable
{
    public int Id { get; set; }

    public int CurrentUserId { get; set; }

    public int CurrentStateId { get; set; }

    public int UserId { get; set; }

    public int? VekaletId { get; set; }

    public DateOnly? GidisTarihi { get; set; }

    public DateOnly? DonusTarihi { get; set; }

    public int DestinationLocationId { get; set; }

    public string TripDescription { get; set; }

    public string DigerDestination { get; set; }

    public int HereLocationId { get; set; }

    public int TripDescriptionId { get; set; }

    public decimal Avans { get; set; }

    public int OnaySirasi { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int CreatedUserId { get; set; }

    public bool? LastApproved { get; set; }

    public string Disaprovecondition { get; set; }

    public bool? Approval { get; set; }

    public bool Enabled { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual AdminUser CurrentUser { get; set; }

    public virtual HrdestinationLocationTable DestinationLocation { get; set; }

    public virtual HrdestinationLocationTable HereLocation { get; set; }

    public virtual ICollection<HrexpenseDetail> HrexpenseDetails { get; set; } = new List<HrexpenseDetail>();

    public virtual ICollection<HrexpenseTable> HrexpenseTables { get; set; } = new List<HrexpenseTable>();

    public virtual ICollection<HrexpenseTripDetail> HrexpenseTripDetails { get; set; } = new List<HrexpenseTripDetail>();

    public virtual HrtripDescription TripDescriptionNavigation { get; set; }

    public virtual AdminUser User { get; set; }
}