// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrexpenseWithOutTripTable
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public DateOnly? GidisTarihi { get; set; }

    public DateOnly? DonusTarihi { get; set; }

    public int DestinationLocationId { get; set; }

    public string DigerDestination { get; set; }

    public int TripDescriptionId { get; set; }

    public string TripDesciption { get; set; }

    public int? OnaySirasi { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int CreatedUserId { get; set; }

    public bool? Approval { get; set; }

    public bool Enabled { get; set; }

    public bool? LastApproved { get; set; }

    public string TripDescription { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual HrdestinationLocationTable DestinationLocation { get; set; }

    public virtual ICollection<HrexpenseWithOutDetail> HrexpenseWithOutDetails { get; set; } = new List<HrexpenseWithOutDetail>();

    public virtual ICollection<HrexpenseWithOutTable> HrexpenseWithOutTables { get; set; } = new List<HrexpenseWithOutTable>();

    public virtual HrtripDescription TripDescriptionNavigation { get; set; }

    public virtual AdminUser User { get; set; }
}