// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrexpenseTypeTable
{
    public int Id { get; set; }

    public string ExpenseTypeName { get; set; }

    public bool ToplamaNo { get; set; }

    public bool HarcamaBoyu { get; set; }

    public bool OtoparkMi { get; set; }

    public string SapSide { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<HrexpenseAmount> HrexpenseAmounts { get; set; } = new List<HrexpenseAmount>();

    public virtual ICollection<HrexpenseTable> HrexpenseTables { get; set; } = new List<HrexpenseTable>();

    public virtual ICollection<HrexpenseWithOutTable> HrexpenseWithOutTables { get; set; } = new List<HrexpenseWithOutTable>();
}