// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrmaasTablosu
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Gorevi { get; set; }

    public string Unvani { get; set; }

    public DateOnly DogumTarihi { get; set; }

    public DateOnly IseGirisTarihi { get; set; }

    public string Lokasyon { get; set; }

    public string UcretTuru { get; set; }

    public decimal? Maas { get; set; }

    public decimal? Kira { get; set; }

    public decimal? YuksekLisans { get; set; }

    public decimal? YabanciDil { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }
}