// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrsgkPrim
{
    public int Id { get; set; }

    public decimal SgkIsverenPayi { get; set; }

    public decimal SgkIssizlikIsv { get; set; }

    public decimal SgkIsciPayi { get; set; }

    public decimal SgkIssizlikIsci { get; set; }

    public decimal? DamgaVergisi { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }
}