// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrtripDescription
{
    public int Id { get; set; }

    public int SapId { get; set; }

    public string TripDescription { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<HrexpenseTripTable> HrexpenseTripTables { get; set; } = new List<HrexpenseTripTable>();

    public virtual ICollection<HrexpenseWithOutTripTable> HrexpenseWithOutTripTables { get; set; } = new List<HrexpenseWithOutTripTable>();
}