// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrvergiDilimleriTable
{
    public int Id { get; set; }

    public int Yil { get; set; }

    public decimal? VergiDilimi5 { get; set; }

    public decimal MatrahSiniri5 { get; set; }

    public decimal? VergiDilimi4 { get; set; }

    public decimal MatrahSiniri4 { get; set; }

    public decimal? VergiDilimi3 { get; set; }

    public decimal MatrahSiniri3 { get; set; }

    public decimal? VergiDilimi2 { get; set; }

    public decimal MatrahSiniri2 { get; set; }

    public decimal? VergiDilimi1 { get; set; }

    public decimal MatrahSiniri1 { get; set; }

    public decimal? SgkTavan { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }
}