// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class HrvekaletTable
{
    public int Id { get; set; }

    public int VekaletVerenId { get; set; }

    public int VekaletAlanId { get; set; }

    public DateOnly? Tarih { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser VekaletAlan { get; set; }

    public virtual AdminUser VekaletVeren { get; set; }
}