// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class IcYazismalarMesajTable
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int? IcYazismaId { get; set; }

    public string Message { get; set; }

    public int? SendUserId { get; set; }

    public bool? ShowAll { get; set; }

    public int? UserId { get; set; }
}