// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class IncomingDocument
{
    public int Id { get; set; }

    public string DocumentNumber { get; set; }

    public bool IsOutgoing { get; set; }

    public int DocumentOrder { get; set; }

    public int? CompanyId { get; set; }

    public int? UserId { get; set; }

    public string UserIds { get; set; }

    public DateTime IncomingDate { get; set; }

    public int? TypeId { get; set; }

    public bool HasAttachment { get; set; }

    public int? SourceId { get; set; }

    public string Title { get; set; }

    public string Notes { get; set; }

    public DateOnly? DocumentDate { get; set; }

    public string DocumentSpecialNumber { get; set; }

    public string Due { get; set; }

    public DateOnly? DueDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsRead { get; set; }

    public DateOnly? ReadDate { get; set; }

    public bool IsCompleted { get; set; }

    public DateOnly? CompletedDate { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual Company Company { get; set; }

    public virtual IncomingDocumentSource Source { get; set; }

    public virtual IncomingDocumentType Type { get; set; }

    public virtual AdminUser User { get; set; }
}