// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class IsgaksiyonTakipTable
{
    public int Id { get; set; }

    public double OncekiOlasilik { get; set; }

    public double OncekiSiklik { get; set; }

    public double OncekiSiddet { get; set; }

    public double OncekiRisk { get; set; }

    public int AksiyonId { get; set; }

    public string AksiyonSorumlulari { get; set; }

    public DateOnly? PlanlananTarih { get; set; }

    public DateOnly? GerceklesenTarih { get; set; }

    public string KisaAciklama { get; set; }

    public string AlinmasiGerekenOnlemler { get; set; }

    public int? Oncelik { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual IsgaksiyonTable Aksiyon { get; set; }
}