// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class IsgaksiyonTable
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int UygunsuzlukKaynagiId { get; set; }

    public DateOnly? UygunsuzlukTarihi { get; set; }

    public int UygunsuzlukBulunanUniteId { get; set; }

    public int BidirimdeBulunan { get; set; }

    public string UygunsuzlukAciklama { get; set; }

    public string UygunsuzlukOneri { get; set; }

    public string FileOnceki { get; set; }

    public string FileSonraki { get; set; }

    public bool BittiMi { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser BidirimdeBulunanNavigation { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<IsgaksiyonTakipTable> IsgaksiyonTakipTables { get; set; } = new List<IsgaksiyonTakipTable>();

    public virtual SectionTable UygunsuzlukBulunanUnite { get; set; }

    public virtual IsguygunsuzlukKaynagiTable UygunsuzlukKaynagi { get; set; }
}