// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class MusteriSikayetKapatma
{
    public int Id { get; set; }

    public string KapatmaAdi { get; set; }

    public int FabrikaId { get; set; }

    public int DirectorId { get; set; }

    public int CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual AdminUser Director { get; set; }

    public virtual Company Fabrika { get; set; }
}