// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class MusteriSikayetForm
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    public string Title { get; set; }

    public string MusteriKodu { get; set; }

    public string MusteriAdi { get; set; }

    public int CompanyId { get; set; }

    public int SikayetTipiId { get; set; }

    public string MalzemeTuru { get; set; }

    public decimal? MalzemeMiktari { get; set; }

    public int UserId { get; set; }

    public string MusteriTemsilcisi { get; set; }

    public string MusteriTel { get; set; }

    public string MusteriEmail { get; set; }

    public bool Enabled { get; set; }

    public string Description { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual MusteriSikayetCategory Category { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<MusteriSikayetAction> MusteriSikayetActions { get; set; } = new List<MusteriSikayetAction>();

    public virtual MusteriSikayetTipi SikayetTipi { get; set; }

    public virtual AdminUser User { get; set; }
}