// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class MusteriSikayetCategory
{
    public int Id { get; set; }

    public string CategoryName { get; set; }

    public int CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual ICollection<MusteriSikayetEmail> MusteriSikayetEmails { get; set; } = new List<MusteriSikayetEmail>();

    public virtual ICollection<MusteriSikayetForm> MusteriSikayetForms { get; set; } = new List<MusteriSikayetForm>();

    public virtual ICollection<MusteriSikayetTipi> MusteriSikayetTipis { get; set; } = new List<MusteriSikayetTipi>();
}