// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class MusteriSikayetAction
{
    public int Id { get; set; }

    public int SikayetId { get; set; }

    public int AksiyonTipiId { get; set; }

    public string ActionDescription { get; set; }

    public DateOnly? ActionDate { get; set; }

    public int CompanyId { get; set; }

    public int CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual MusteriSikayetAksiyonTipi AksiyonTipi { get; set; }

    public virtual Company Company { get; set; }

    public virtual AdminUser CreatedUser { get; set; }

    public virtual MusteriSikayetForm Sikayet { get; set; }
}