// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class ParaBirimiTable
{
    public int Id { get; set; }

    public string ParaBirimi { get; set; }

    public string ParaDuzeni { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<SozlesmeTable> SozlesmeTableOdemeAvansBirimis { get; set; } = new List<SozlesmeTable>();

    public virtual ICollection<SozlesmeTable> SozlesmeTableSozlesmeTutarBirimis { get; set; } = new List<SozlesmeTable>();

    public virtual ICollection<SozlesmeTable> SozlesmeTableTeminatTutariParaBirims { get; set; } = new List<SozlesmeTable>();
}