// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class RatingQuestionVote
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int RatingId { get; set; }

    public int QuestionId { get; set; }

    public int RatingValue { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual RatingQuestion Question { get; set; }

    public virtual Rating Rating { get; set; }

    public virtual AdminUser User { get; set; }
}