// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class Rating
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Approval { get; set; }

    public bool Enabled { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public bool? IsBeyazYaka { get; set; }

    public bool? IsMaviYaka { get; set; }

    public virtual ICollection<RatingQuestionVote> RatingQuestionVotes { get; set; } = new List<RatingQuestionVote>();

    public virtual ICollection<RatingQuestion> RatingQuestions { get; set; } = new List<RatingQuestion>();
}