// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class RatingQuestion
{
    public int Id { get; set; }

    public int RatingId { get; set; }

    public string Title { get; set; }

    public int PuanGorusGosterimi { get; set; }

    public int Count { get; set; }

    public decimal Average { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Approval { get; set; }

    public bool Enabled { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual Rating Rating { get; set; }

    public virtual ICollection<RatingQuestionVote> RatingQuestionVotes { get; set; } = new List<RatingQuestionVote>();
}