// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class RepresentativeExpenseTable
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int CurrentUserId { get; set; }

    public int CurrentStateId { get; set; }

    public DateOnly? SpendingTime { get; set; }

    public int TypeId { get; set; }

    public string Description { get; set; }

    public decimal Amount { get; set; }

    public decimal ApprovedAmount { get; set; }

    public bool Approval { get; set; }

    public int OnaySirasi { get; set; }

    public string FileNames { get; set; }

    public string DisaproveCondition { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser CurrentUser { get; set; }

    public virtual ICollection<RepresentativeExpenseDetail> RepresentativeExpenseDetails { get; set; } = new List<RepresentativeExpenseDetail>();

    public virtual RepresentativeExpenseType Type { get; set; }

    public virtual AdminUser User { get; set; }
}