// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class RepresentativeExpenseDetail
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public int RepId { get; set; }

    public int? VekaletUserId { get; set; }

    public int UserId { get; set; }

    public bool? Approved { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsReplied { get; set; }

    public DateTime? ReplyDate { get; set; }

    public string Description { get; set; }

    public bool Enabled { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual RepresentativeExpenseTable Rep { get; set; }

    public virtual AdminUser User { get; set; }
}