// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class SaticiFirmalarTable
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public string FirmaKodu { get; set; }

    public string FirmaAdi { get; set; }

    public string Iletisim { get; set; }

    public string Yetkilisi { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual Company Company { get; set; }
}