// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class SevkiyatPlaka
{
    public int Id { get; set; }

    public string PlakaNo { get; set; }

    public string UrunTipi { get; set; }

    public string UrunCinsi { get; set; }

    public DateOnly? AracCikis { get; set; }

    public bool ListedeMi { get; set; }

    public int CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Enabled { get; set; }

    public int? SortOrder { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser CreatedUser { get; set; }
}