// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class SozlesmeTable
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int SozlesmeTuruId { get; set; }

    public string SatinAlmaGrubu { get; set; }

    public string FirmaKodu { get; set; }

    public string Iletisim { get; set; }

    public string FirmaYetkilisi { get; set; }

    public string SozlesmeKonusu { get; set; }

    public string Aciklama { get; set; }

    public decimal SozlesmeTutari { get; set; }

    public int SozlesmeTutarBirimiId { get; set; }

    public int SozlesmeOdemeVadesi { get; set; }

    public decimal? OdemeAvansYuzdesi { get; set; }

    public decimal OdemeAvansTutari { get; set; }

    public int OdemeAvansBirimiId { get; set; }

    public string DamgaVergisiOdemesi { get; set; }

    public DateOnly ImzalananTarih { get; set; }

    public DateOnly BaslangicTarihi { get; set; }

    public DateOnly BitisTarihi { get; set; }

    public DateOnly UyariTarihi { get; set; }

    public string BildirimYapilacakKisiler { get; set; }

    public bool TeminatVarmi { get; set; }

    public DateOnly? TeminatBaslangic { get; set; }

    public DateOnly? TeminatBitis { get; set; }

    public decimal? TeminatTutari { get; set; }

    public int? TeminatTutariParaBirimId { get; set; }

    public bool TamamMi { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual Company Company { get; set; }

    public virtual ParaBirimiTable OdemeAvansBirimi { get; set; }

    public virtual SozlesmeCinsiTable SozlesmeTuru { get; set; }

    public virtual ParaBirimiTable SozlesmeTutarBirimi { get; set; }

    public virtual ParaBirimiTable TeminatTutariParaBirim { get; set; }
}