// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class SureliIsTakipTable
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public string IsinTanimi { get; set; }

    public DateOnly BaslamaTarihi { get; set; }

    public DateOnly TerminTarihi { get; set; }

    public int MailSuresi { get; set; }

    public string TakipSorumlusu { get; set; }

    public string Muhattaplar { get; set; }

    public bool Tamamlandi { get; set; }

    public string Aciklama { get; set; }

    public int CreatedUserId { get; set; }

    public string MailIds { get; set; }

    public string Files { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public bool? SurekliMi { get; set; }

    public virtual Company Company { get; set; }

    public virtual AdminUser CreatedUser { get; set; }
}