// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class TahsilatRaporuTable
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string Belnr { get; set; }

    public string Blart { get; set; }

    public string Budat { get; set; }

    public string Bukrs { get; set; }

    public string Buzei { get; set; }

    public decimal? Dmbe2 { get; set; }

    public decimal? Dmbe3 { get; set; }

    public decimal? Dmbtr { get; set; }

    public string Gjahr { get; set; }

    public string Hkont { get; set; }

    public string Hwae2 { get; set; }

    public string Hwae3 { get; set; }

    public string Hwaer { get; set; }

    public string Kunnr { get; set; }

    public string Lifnr { get; set; }

    public string Name1 { get; set; }

    public string Sgtxt { get; set; }

    public string Shkzg { get; set; }

    public string Waers { get; set; }

    public decimal? Wrbtr { get; set; }

    public string Zuonr { get; set; }
}