// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class ToplantiKararlari
{
    public int Id { get; set; }

    public int KararNo { get; set; }

    public int? CompanyId { get; set; }

    public int ToplantiNo { get; set; }

    public DateOnly? ToplantiTarihi { get; set; }

    public int ToplantiYeriId { get; set; }

    public string ToplantiKonusu { get; set; }

    public string Katilimcilar { get; set; }

    public int? SorumluDepartmanId { get; set; }

    public string YapilacakIs { get; set; }

    public string Isdurumu { get; set; }

    public string BaslangicSuresi { get; set; }

    public string BitisSuresi { get; set; }

    public string Durumu { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ToplantiYeriTable ToplantiYeri { get; set; }
}