// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class TransferPaymentKalemSaptable
{
    public int Id { get; set; }

    public int CurrentStateId { get; set; }

    public int CurrentUserId { get; set; }

    public string Henum { get; set; }

    public string Posnr { get; set; }

    public string Firma { get; set; }

    public string Lifnr { get; set; }

    public string Banka { get; set; }

    public string Bankl { get; set; }

    public string Brnch { get; set; }

    public string Bankn { get; set; }

    public string Iban { get; set; }

    public string Wrbtr { get; set; }

    public string Waerk { get; set; }

    public string Aciklama { get; set; }

    public bool? Approval { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int? TransferPaymentSap { get; set; }

    public virtual ICollection<ActiveTransferDetail> ActiveTransferDetails { get; set; } = new List<ActiveTransferDetail>();

    public virtual TransferPaymentSaptable HenumNavigation { get; set; }
}