// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class UserTelephoneTable
{
    public int Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public bool Enabled { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public string FactoryInternal { get; set; }

    public string FactoryNumber { get; set; }

    public string PhoneNumber { get; set; }

    public string ShortCode { get; set; }

    public int UserId { get; set; }

    public bool? KvkkOnay { get; set; }

    public string Image { get; set; }

    public virtual AdminUser User { get; set; }
}