// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class UserForm
{
    public int Id { get; set; }

    public int UserFormTypeId { get; set; }

    public int UserId { get; set; }

    public string FormDataTemplate { get; set; }

    public string FormDataForReport { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Term { get; set; }

    public bool IsOk { get; set; }

    public bool Enabled { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual AdminUser User { get; set; }

    public virtual UserFormType UserFormType { get; set; }
}