// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class UserFormType
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public bool Enabled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public virtual ICollection<UserFormTemplate> UserFormTemplates { get; set; } = new List<UserFormTemplate>();

    public virtual ICollection<UserForm> UserForms { get; set; } = new List<UserForm>();
}