// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AskalePortal.API.Models;

public partial class VersionTable
{
    public int Id { get; set; }

    public int Type { get; set; }

    public int Platform { get; set; }

    public string CurrentVersion { get; set; }

    public bool Enabled { get; set; }
}